In [1]:
#Library import.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import string

In [2]:
#Data import.
data = pd.read_csv('Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.csv')

In [3]:
#Visual inspection of the first 50 rows.
data.head(50)

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,"62,000",NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
6,4/27/2021 11:02:51,25-34,Publishing,Publishing Assistant,NaN,"33,000",2000.0,USD,NaN,NaN,USA,South Carolina,Columbia,2 - 4 years,2 - 4 years,College degree,Woman,White
7,4/27/2021 11:03:00,25-34,Education (Primary/Secondary),Librarian,"High school, FT","50,000",NaN,USD,NaN,NaN,United States,Arizona,Yuma,5-7 years,5-7 years,Master's degree,Man,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
9,4/27/2021 11:03:02,35-44,"Accounting, Banking & Finance",Senior Accountant,NaN,"45,000",0.0,USD,NaN,I work for a Charter School,United States,Florida,Palm Coast,21 - 30 years,21 - 30 years,College degree,Woman,"Hispanic, Latino, or Spanish origin, White"
10,4/27/2021 11:03:03,25-34,Nonprofits,Office Manager,NaN,"47,500",0.0,USD,NaN,NaN,United States,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
11,4/27/2021 11:03:07,35-44,Education (Higher Education),Deputy Title IX Coordinator/ Assistant Directo...,NaN,"62,000",0.0,USD,NaN,NaN,USA,Pennsylvania,Scranton,11 - 20 years,5-7 years,PhD,Woman,"Hispanic, Latino, or Spanish origin, White"
12,4/27/2021 11:03:09,35-44,"Accounting, Banking & Finance",Manager of Information Services,NaN,"100,000",0.0,USD,NaN,NaN,United States,Michigan,Detroit,11 - 20 years,11 - 20 years,College degree,Man,"Asian or Asian American, White"
13,4/27/2021 11:03:10,25-34,Law,Legal Aid Staff Attorney,non-profit law firm,"52,000",0.0,USD,NaN,NaN,United States,Minnesota,Saint Paul,2 - 4 years,2 - 4 years,NaN,Woman,White
14,4/27/2021 11:03:11,18-24,Health care,Patient care coordinator,NaN,"32,000",NaN,CAD,NaN,NaN,Canada,NaN,Remote,1 year or less,1 year or less,College degree,Woman,White
15,4/27/2021 11:03:11,35-44,Utilities & Telecommunications,Quality And Compliance Specialist,NaN,"24,000",500.0,GBP,NaN,NaN,United Kingdom,NaN,Lincoln,11 - 20 years,5-7 years,College degree,Man,White
16,4/27/2021 11:03:13,35-44,Business or Consulting,Executive Assistant,NaN,"85,000",5000.0,USD,NaN,NaN,USA,Illinois,Chicago,8 - 10 years,8 - 10 years,Some college,Woman,White
17,4/27/2021 11:03:19,45-54,Art & Design,graphic designer,NaN,"59,000",NaN,USD,NaN,NaN,usa,California,Pomona,21 - 30 years,21 - 30 years,College degree,Woman,White
18,4/27/2021 11:03:21,35-44,Business or Consulting,Senior Manager,NaN,"98,000",1000.0,USD,NaN,NaN,USA,Georgia,Atlanta,11 - 20 years,2 - 4 years,Master's degree,Woman,White
19,4/27/2021 11:03:23,35-44,Education (Higher Education),Assistant Director of Academic Advising,NaN,"54,000",NaN,USD,NaN,NaN,United States,Florida,Boca Raton,11 - 20 years,11 - 20 years,Master's degree,Woman,White
20,4/27/2021 11:03:24,25-34,Health care,Data Programmer Analyst,NaN,"74,000",0.0,USD,NaN,NaN,USA,Pennsylvania,Philadelphia,5-7 years,5-7 years,Master's degree,Woman,White
21,4/27/2021 11:03:24,35-44,Nonprofits,Program Coordinator & Assistant Editor,NaN,"50,000",NaN,USD,NaN,NaN,United States,NaN,Atlanta,5-7 years,2 - 4 years,PhD,Woman,White
22,4/27/2021 11:03:27,35-44,Nonprofits,Event Planner,NaN,"63,000",NaN,CAD,NaN,NaN,Canada,NaN,Toronto,11 - 20 years,8 - 10 years,Master's degree,Woman,White
23,4/27/2021 11:03:29,35-44,Government and Public Administration,Researcher,NaN,"96,000",1000.0,USD,NaN,NaN,United States,Ohio,Dayton,8 - 10 years,2 - 4 years,PhD,Woman,Asian or Asian American
24,4/27/2021 11:03:31,25-34,Public Library,Teen Librarian,NaN,"44,500",0.0,USD,NaN,NaN,US,Florida,Bradenton,5-7 years,2 - 4 years,NaN,Woman,White
25,4/27/2021 11:03:34,35-44,Education (Higher Education),Communications Specialist,NaN,"60,000",0.0,USD,NaN,NaN,USA,Michigan,Ann Arbor,11 - 20 years,1 year or less,Master's degree,Woman,White
26,4/27/2021 11:03:38,25-34,Nonprofits,Program Director,I manage staff members who each manage 8-15 ot...,"62,000",NaN,USD,NaN,NaN,US,District of Columbia,Washington DC,5-7 years,2 - 4 years,College degree,Man,White
27,4/27/2021 11:03:40,35-44,Law,Bookkeeper/Billing Manager,NaN,"48,000",4000.0,USD,NaN,NaN,USA,Maryland,Silver Spring,11 - 20 years,2 - 4 years,College degree,Woman,Another option not listed here or prefer not t...
28,4/27/2021 11:03:41,35-44,Government and Public Administration,Economist,NaN,"140,000",NaN,USD,NaN,NaN,USA,District of Columbia,Washington,11 - 20 years,11 - 20 years,Master's degree,Woman,White
29,4/27/2021 11:03:43,25-34,Engineering or Manufacturing,Research Engineer,NaN,"80,000",NaN,USD,NaN,NaN,United States,Texas,San Antonio,5-7 years,5-7 years,College degree,Woman,White
30,4/27/2021 11:03:44,25-34,Nonprofits,Volunteer and Giving Coordinator,NaN,"39,000",NaN,USD,NaN,NaN,United States,Minnesota,Minneapolis,2 - 4 years,2 - 4 years,College degree,Woman,White
31,4/27/2021 11:03:44,35-44,Media & Digital,Editor,NaN,"125,000",0.0,USD,NaN,NaN,USA,District of Columbia,"Washington, DC",11 - 20 years,8 - 10 years,Master's degree,Woman,White
32,4/27/2021 11:03:45,25-34,"Accounting, Banking & Finance",Financial Advisor,NaN,"230,000",NaN,USD,NaN,Commission based,USA,Missouri,St. Louis,11 - 20 years,11 - 20 years,College degree,Woman,White
33,4/27/2021 11:03:46,35-44,"Accounting, Banking & Finance",Accounting Manager,NaN,"110,000",15000.0,USD,NaN,NaN,US,Virginia,Richmond,21 - 30 years,11 - 20 years,College degree,Woman,White
34,4/27/2021 11:03:54,25-34,Nonprofits,Administrative and HR Manager,NaN,"50,000",NaN,USD,NaN,NaN,United States,District of Columbia,Washington,5-7 years,2 - 4 years,College degree,Woman,White
35,4/27/2021 11:03:55,35-44,Education (Higher Education),Senior IRB Analyst,"State university, higher ed research adminstra...","68,000",0.0,USD,NaN,NaN,USA,North Carolina,Research Triangle,5-7 years,2 - 4 years,Master's degree,Woman,White
36,4/27/2021 11:03:56,18-24,Media & Digital,Reporter,NaN,"41,000",100.0,USD,NaN,NaN,United States,Michigan,Kalamazoo,2 - 4 years,2 - 4 years,College degree,Woman,White
37,4/27/2021 11:03:57,25-34,"Accounting, Banking & Finance",Senior Administrator,NaN,"76,000",10000.0,USD,NaN,NaN,United States,New York,Manhattan,5-7 years,2 - 4 years,College degree,Woman,White
38,4/27/2021 11:03:57,35-44,Government and Public Administration,Staff Services Manager II,"Mid-level manager, team of 13","78,000",0.0,USD,NaN,NaN,USA,California,Sacramento,8 - 10 years,5-7 years,Master's degree,Woman,White
39,4/27/2021 11:03:59,25-34,"Accounting, Banking & Finance",Receptionist,NaN,"37,000",0.0,USD,NaN,NaN,USA,Texas,Dallas,2 - 4 years,2 - 4 years,College degree,Woman,White
40,4/27/2021 11:04:01,45-54,Engineering or Manufacturing,Lead Engineer,supervisor level with no direct reports,"100,000",50000.0,USD,NaN,NaN,USA,Georgia,waynesboro,21 - 30 years,21 - 30 years,College degree,Woman,White
41,4/27/2021 11:04:01,35-44,"Marketing, Advertising & PR",Senior Copywriter,NaN,"35,000",6000.0,GBP,NaN,NaN,UK,NaN,Liverpool,11 - 20 years,11 - 20 years,College degree,Woman,White
42,4/27/2021 11:04:02,25-34,Government and Public Administration,Manager of Data Integrity and Prospect Research,NaN,"65,000",0.0,USD,NaN,NaN,USA,Virginia,Richmond,5-7 years,5-7 years,College degree,Man,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
45,4/27/2021 11:04:04,25-34,Nonprofits,Project Manager,NaN,"66,625",1500.0,USD,NaN,NaN,US,Massachusetts,Boston,8 - 10 years,8 - 10 years,College degree,Woman,"Hispanic, Latino, or Spanish origin, White"
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
48,4/27/2021 11:04:10,25-34,Engineering or Manufacturing,Engineering specialist,NaN,"120,000",1500.0,CAD,NaN,NaN,Canada,NaN,Vancouver,11 - 20 years,8 - 10 years,College degree,Woman,White
49,4/27/2021 11:04:10,25-34,Retail,"Manager, Total Rewards",NaN,"97,500",10000.0,CAD,NaN,NaN,Canada,NaN,Toronto,8 - 10 years,8 - 10 years,College degree,Woman,White

In [4]:
##Data Cleaning

#Fill missing information.
data.iloc[:, 6] = data.iloc[:, 6].fillna(0)
data.iloc[:, 4] = data.iloc[:, 4].fillna('No context needed')
data.iloc[:, 9] = data.iloc[:, 9].fillna('No context needed')
data.iloc[:, 11] = data.iloc[:, 11].fillna('Not provided')

In [5]:
#Checking for unique values in the "Country" column so I can standardize the values.
print(data.iloc[:, 10].unique())

['United States' 'United Kingdom' 'US' 'USA' 'Canada' 'United Kingdom '
 'usa' 'UK' 'Scotland ' 'U.S.' 'United States ' 'The Netherlands'
 'Australia ' 'Spain' 'us' 'Usa' 'England' 'finland'
 'United States of America' 'France' 'United states' 'Scotland' 'USA '
 'United states ' 'Germany' 'UK ' 'united states' 'Ireland' 'India'
 'Australia' 'Uk' 'United States of America ' 'U.S. ' 'canada' 'Canada '
 'U.S>' 'ISA' 'Argentina' 'Great Britain ' 'US ' 'United State' 'U.S.A'
 'Denmark' 'U.S.A.' 'America' 'Netherlands' 'netherlands' 'England '
 'united states of america' 'Ireland ' 'Switzerland' 'Netherlands '
 'Bermuda' 'Us' 'The United States' 'United State of America' 'Germany '
 'Malaysia' 'Mexico ' 'United Stated' 'South Africa ' 'Belgium'
 'Northern Ireland' 'u.s.' 'South Africa' 'UNITED STATES' 'united States'
 'Sweden' 'Hong Kong' 'Kuwait' 'Norway' 'Sri lanka' 'Contracts'
 'USA-- Virgin Islands' 'United Statws' 'England/UK' 'U.S'
 "We don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were located"
 'Unites States ' 'Usa ' 'U.S.A. ' 'England, UK.' 'Greece' 'Japan'
 'U. S. ' 'Britain ' 'United Sates' 'Japan ' 'Austria' 'Brazil'
 'Canada, Ottawa, ontario' 'Global' 'Sweden ' 'United States of American '
 'FRANCE' 'Uniited States' 'United Kingdom (England)'
 'Worldwide (based in US but short term trips aroudn the world)' 'CANADA '
 'Canadw' 'Hungary' 'Luxembourg' 'United Sates of America' 'ireland'
 'United States (I work from home and my clients are all over the US/Canada/PR'
 'Colombia' 'CANADA' 'Unted States' 'germany' 'United Statesp'
 'United Stattes' 'United Statea' 'United Kingdom.' 'Mexico' 'New Zealand'
 'Trinidad and Tobago' 'Unites States' 'United Statees' 'United kingdom'
 'Cayman Islands' 'UNited States' 'Can'
 'I am located in Canada but I work for a company in the US'
 'United kingdom ' 'Uniyed states' 'Uniyes States'
 'United States of Americas' 'U.A.' 'Czech republic' 'Czechia' 'Latvia'
 'Finland' 'U. S.' 'Puerto Rico' 'US of A' 'Rwanda'
 'United States of america ' 'United Arab Emirates ' 'Bangladesh '
 'Spain ' 'U.K. ' 'Romania' 'U.SA' 'United Kindom' 'United Status'
 'New Zealand ' 'Currently finance' ' U.S.' 'Serbia' 'Philippines'
 'Russia ' 'Poland' 'UXZ' 'czech republic' 'England, UK' 'Turkey' 'Canda'
 'Puerto Rico ' 'Canada and USA' 'Catalonia'
 '$2,175.84/year is deducted for benefits' 'uk' 'France ' 'Italy (South)'
 'Jersey, Channel islands' 'Uk ' 'China' 'Virginia' 'Afghanistan' 'Israel'
 'U.s.' 'Great Britain' 'U.s.a.' 'USS' 'Denmark ' 'Uniteed States'
 'New Zealand Aotearoa' 'U.K.' 'Hartford' 'Japan, US Gov position'
 'Csnada' 'United Stares' 'New zealand' 'Mainland China' 'I.S.'
 'UK (Northern Ireland)' 'UK for U.S. company' ' US' 'Unites states ' 'NZ'
 'Us ' 'Hong Kong ' 'Taiwan' 'Canad' 'Unite States' 'australia' 'The US'
 'united states ' 'The Netherlands ' 'Cambodia'
 'United states of America ' 'Vietnam' 'Remote' 'Singapore' 'South Korea'
 'Czech Republic ' 'Thailand' 'Bangladesh' 'Lithuania' 'Eritrea'
 'Indonesia' 'Singapore '
 'For the United States government, but posted overseas' 'IS'
 'Switzerland ' 'United Kingdomk' 'Italy' ' New Zealand' 'Cuba' 'Slovenia'
 'Australi' "Cote d'Ivoire" 'united kingdom'
 'From Romania, but for an US based company' 'Somalia'
 'Wales (United Kingdom)' 'England, Gb' 'Czech Republic' 'UnitedStates'
 'Sri Lanka' 'spain' 'Danmark' 'U.K. (northern England)' 'U.K' 'NL'
 'the Netherlands' 'Nederland' 'Slovakia' 'United States of america'
 'Portugal ' 'England, United Kingdom' 'Sierra Leone' 'Englang'
 'United statew' 'UAE' 'Belgium '
 'bonus based on meeting yearly goals set w/ my supervisor'
 'International ' 'The Bahamas ' 'Wales'
 "I earn commission on sales. If I meet quota, I'm guaranteed another 16k min. Last year i earned an additional 27k. It's not uncommon for people in my space to earn 100k+ after commission. "
 'Costa Rica' ' United States' 'United Statues' 'Untied States'
 'USA (company is based in a US territory, I work remote)' 'Chile'
 'denmark' 'UK (England)' 'UK, remote' 'Scotland, UK' 'USAB'
 'Unitied States' 'Norway ' 'Qatar' 'United Sttes' 'Remote (philippines)'
 'Brazil ' 'Unites kingdom ' 'South africa' 'Portugal' 'united stated'
 'United States Of America' 'Nigeria' 'Panamá' 'Northern Ireland '
 'england' 'SWITZERLAND'
 'Austria, but I work remotely for a Dutch/British company'
 "I work for an US based company but I'm from Argentina."
 'I was brought in on this salary to help with the EHR and very quickly was promoted to current position but compensation was not altered. '
 'Uniter Statez' 'U. S ' 'Congo' 'United states of America' 'Uruguay'
 'Pakistan' 'Brasil' 'USA tomorrow ' 'United Stateds'
 'n/a (remote from wherever I want)' 'singapore'
 'US govt employee overseas, country withheld' 'usa ' 'Malaysia ' 'Uganda'
 'Malta' 'Saudi Arabia' 'Bulgaria' 'Estonia' 'Morocco' 'new zealand'
 'Africa' 'Ecuador' 'Zimbabwe' 'Ghana' 'San Francisco' 'Usat' '🇺🇸 '
 'Luxemburg' 'Unitef Stated' 'UA' 'Wales, UK' 'United Stares ' 'Croatia '
 'England, United Kingdom ' 'United STates' 'USaa' 'uSA' 'South Korea '
 'The netherlands' 'Ukraine ' 'america' 'switzerland'
 'United States- Puerto Rico'
 'From New Zealand but on projects across APAC' 'Y' 'United y'
 'Wales (UK)' 'Isle of Man' 'Northern Ireland, United Kingdom' 'europe'
 'California ' 'UK, but for globally fully remote company' 'Australian '
 'México' 'Jamaica' 'uS' 'USD' 'the netherlands'
 "USA, but for foreign gov't" 'japan' 'Kenya' 'Jordan' 'United Statss'
 'ARGENTINA BUT MY ORG IS IN THAILAND' 'United states of america' 'UsA'
 'I work for a UAE-based organization, though I am personally in the US.'
 'United  States' 'france' 'Aotearoa New Zealand' 'na' 'Policy' 'Cyprus'
 'hong konh' 'United States is America' 'Liechtenstein'
 'Company in Germany. I work from Pakistan.' 'croatia' 'Canadá' 'ENGLAND'
 'United States of American' 'U.S.A ' 'INDIA' 'Bosnia and Herzegovina'
 'NIGERIA' 'Poland ']

In [6]:
#Trimming spaces
data.iloc[:, 10] = data.iloc[:, 10].apply(lambda x: x.strip())

In [7]:
#Fixing data in the wrong column. I searched for each misplaced value and used the row index to do a visual inspection.
#This is just to make sure I put the information in the correct column.
row_index = data.loc[data.iloc[:, 10] == 'Contracts'].index[0]

In [8]:
#Visual inspection of the row.
print(data.iloc[row_index, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 11:35:42
How old are you?                                                                                                                                                                                                                                                                    45-54
What industry do you work in?                                                                                                                                                                                                                        Government and Public Administration
Job title                                                                                                                                                                                                                                                      Mission Support Specialist
If your job title needs additional context, please clarify here:                                                                                                                                                                                                        No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               88,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                     1000.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                                        NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                    Contracts
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                    District of Columbia
What city do you work in?                                                                                                                                                                                                                                                              DC
How many years of professional work experience do you have overall?                                                                                                                                                                                                         21 - 30 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                   11 - 20 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                             Another option not listed here or prefer not t...
Name: 1971, dtype: object

In [9]:
#Replacing values in the correct column.
data.iloc[row_index, 9] = data.iloc[row_index, 10]
data.iloc[row_index, 10] = 'United States'

In [10]:
#Finding the next value. This process is repeated with each incorrect value.
row_index1 = data.loc[data.iloc[:, 10] == "We don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were located"].index[0]

In [11]:
print(data.iloc[row_index1, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 11:40:54
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                               Accounting, Banking & Finance
Job title                                                                                                                                                                                                                                                       Senior Banking Associate
If your job title needs additional context, please clarify here:                                                                                                                                                                        Assistant branch manager, they just don't like...
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               37,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                    37000.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                                        NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                            We don't get raises, we get quarterly bonuses,...
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                           Massachusetts
What city do you work in?                                                                                                                                                                                                                                                         Mashpee
How many years of professional work experience do you have overall?                                                                                                                                                                                                          8 - 10 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 2249, dtype: object

In [12]:
data.iloc[row_index1, 9] = data.iloc[row_index1, 10]
data.iloc[row_index1, 10] = 'United States'

In [13]:
row_index2 = data.loc[data.iloc[:, 10] == 'Currently finance'].index[0]

In [14]:
print(data.iloc[row_index2, :])

Timestamp                                                                                                                                                                                                                                        4/27/2021 14:44:02
How old are you?                                                                                                                                                                                                                                              45-54
What industry do you work in?                                                                                                                                                                                                           Marketing, Advertising & PR
Job title                                                                                                                                                                                                                                        Digital Specialist
If your job title needs additional context, please clarify here:                                                                                                                                                                                  No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                         90,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                  0.0
Please indicate the currency                                                                                                                                                                                                                                    USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                  NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                  No context needed
What country do you work in?                                                                                                                                                                                                                      Currently finance
If you're in the U.S., what state do you work in?                                                                                                                                                                                                            Oregon
What city do you work in?                                                                                                                                                                                                                                  Portland
How many years of professional work experience do you have overall?                                                                                                                                                                                   11 - 20 years
How many years of professional work experience do you have in your field?                                                                                                                                                                             11 - 20 years
What is your highest level of education completed?                                                                                                                                                                                                   College degree
What is your gender?                                                                                                                                                                                                                                            Man
What is your race? (Choose all that apply.)                                                                                                                                                                                                                   White
Name: 7361, dtype: object

In [15]:
data.iloc[row_index2, 9] = data.iloc[row_index2, 10]
data.iloc[row_index2, 10] = 'United States'

In [16]:
row_index3 = data.loc[data.iloc[:, 10] == '$2,175.84/year is deducted for benefits'].index[0]

In [17]:
print(data.iloc[row_index3, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 15:57:22
How old are you?                                                                                                                                                                                                                                                                    35-44
What industry do you work in?                                                                                                                                                                                                                                Engineering or Manufacturing
Job title                                                                                                                                                                                                                                                         Financial Administrator
If your job title needs additional context, please clarify here:                                                                                                                                                                        bookkeeper, office Manager, all administrative...
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               61,700
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          CAD
If "Other," please indicate the currency here:                                                                                                                                                                                                                                        NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                      $2,175.84/year is deducted for benefits
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                            Not provided
What city do you work in?                                                                                                                                                                                                                                                          Regina
How many years of professional work experience do you have overall?                                                                                                                                                                                                         11 - 20 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                       5-7 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 8383, dtype: object

In [18]:
data.iloc[row_index3, 9] = data.iloc[row_index3, 10]
data.iloc[row_index3, 10] = 'Canada'

In [19]:
row_index4 = data.loc[data.iloc[:, 10] == "I earn commission on sales. If I meet quota, I'm guaranteed another 16k min. Last year i earned an additional 27k. It's not uncommon for people in my space to earn 100k+ after commission."].index[0]

In [20]:
print(data.iloc[row_index4, :])

Timestamp                                                                                                                                                                                                                                                              4/28/2021 11:48:37
How old are you?                                                                                                                                                                                                                                                                    35-44
What industry do you work in?                                                                                                                                                                                                                                                   Insurance
Job title                                                                                                                                                                                                                                                    Associate Account Executive
If your job title needs additional context, please clarify here:                                                                                                                                                                        Licensed insurance producer in a sales role at...
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               51,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                    25000.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                                        NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                            I earn commission on sales. If I meet quota, I...
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                            Pennsylvania
What city do you work in?                                                                                                                                                                                                                                                      Pittsburgh
How many years of professional work experience do you have overall?                                                                                                                                                                                                         11 - 20 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 12925, dtype: object

In [21]:
data.iloc[row_index4, 9] = data.iloc[row_index4, 10]
data.iloc[row_index4, 10] = 'United States'

In [22]:
row_index5 = data.loc[data.iloc[:, 10] == 'I was brought in on this salary to help with the EHR and very quickly was promoted to current position but compensation was not altered.'].index[0]

In [23]:
print(data.iloc[row_index5, :])

Timestamp                                                                                                                                                                                                                                                              4/28/2021 18:41:20
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                                                 Health care
Job title                                                                                                                                                                                                                                                 Director of Revenue Cycle & EHR
If your job title needs additional context, please clarify here:                                                                                                                                                                        I’m over the revenue cycle, handle all EHR iss...
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               72,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                                        NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                            I was brought in on this salary to help with t...
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                             Mississippi
What city do you work in?                                                                                                                                                                                                                                                           Blank
How many years of professional work experience do you have overall?                                                                                                                                                                                                         11 - 20 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                    8 - 10 years
What is your highest level of education completed?                                                                                                                                                                                                                        Master's degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 16853, dtype: object

In [24]:
data.iloc[row_index5, 9] = data.iloc[row_index5, 10]
data.iloc[row_index5, 10] = 'United States'

In [25]:
row_index6 = data.loc[data.iloc[:, 10] == 'bonus based on meeting yearly goals set w/ my supervisor'].index[0]

In [26]:
print(data.iloc[row_index6, :])

Timestamp                                                                                                                                                                                                                                                              4/28/2021 10:01:25
How old are you?                                                                                                                                                                                                                                                                    35-44
What industry do you work in?                                                                                                                                                                                                                                      Business or Consulting
Job title                                                                                                                                                                                                                                                                 Product Manager
If your job title needs additional context, please clarify here:                                                                                                                                                                        firm does consulting, products, and tool-build...
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                              121,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                    10000.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                                        NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                            bonus based on meeting yearly goals set w/ my ...
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                    District of Columbia
What city do you work in?                                                                                                                                                                                                                                                  Washington, DC
How many years of professional work experience do you have overall?                                                                                                                                                                                                         11 - 20 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                       5-7 years
What is your highest level of education completed?                                                                                                                                                                                                                        Master's degree
What is your gender?                                                                                                                                                                                                                                                                  NaN
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 12504, dtype: object

In [27]:
data.iloc[row_index6, 9] = data.iloc[row_index6, 10]
data.iloc[row_index6, 10] = 'United States'

In [28]:
row_index7 = data.loc[data.iloc[:, 10] == 'Policy'].index[0]

In [29]:
print(data.iloc[row_index7, :])

Timestamp                                                                                                                                                                                                                                                 8/14/2021 19:00:16
How old are you?                                                                                                                                                                                                                                                       35-44
What industry do you work in?                                                                                                                                                                                                           Government and Public Administration
Job title                                                                                                                                                                                                                                                          Team Lead
If your job title needs additional context, please clarify here:                                                                                                                                                                                           No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                  112000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                           0.0
Please indicate the currency                                                                                                                                                                                                                                             CAD
If "Other," please indicate the currency here:                                                                                                                                                                                                                           NaN
If your income needs additional context, please provide it here:                                                                                                                                                                                           No context needed
What country do you work in?                                                                                                                                                                                                                                          Policy
If you're in the U.S., what state do you work in?                                                                                                                                                                                                               Not provided
What city do you work in?                                                                                                                                                                                                                                            Toronto
How many years of professional work experience do you have overall?                                                                                                                                                                                             8 - 10 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                       8 - 10 years
What is your highest level of education completed?                                                                                                                                                                                                                       PhD
What is your gender?                                                                                                                                                                                                                                                   Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                            White
Name: 26666, dtype: object

In [30]:
#Forcing upper case and removing punctuation to try and eliminate variation.
data.iloc[:, 10] = data.iloc[:, 10].str.upper()
data.iloc[:, 10] = data.iloc[:, 10].str.translate(str.maketrans('', '', string.punctuation))
print(data.iloc[:, 10])

0         UNITED STATES
1        UNITED KINGDOM
2                    US
3                   USA
4                    US
              ...
27944     UNITED STATES
27945                US
27946                US
27947     UNITED STATES
27948     UNITED STATES
Name: What country do you work in?, Length: 27949, dtype: object

In [31]:
#Checking for unique values again to begin working on mapping dictionary.
print(data.iloc[:, 10].unique())

['UNITED STATES' 'UNITED KINGDOM' 'US' 'USA' 'CANADA' 'UK' 'SCOTLAND'
 'THE NETHERLANDS' 'AUSTRALIA' 'SPAIN' 'ENGLAND' 'FINLAND'
 'UNITED STATES OF AMERICA' 'FRANCE' 'GERMANY' 'IRELAND' 'INDIA' 'ISA'
 'ARGENTINA' 'GREAT BRITAIN' 'UNITED STATE' 'DENMARK' 'AMERICA'
 'NETHERLANDS' 'SWITZERLAND' 'BERMUDA' 'THE UNITED STATES'
 'UNITED STATE OF AMERICA' 'MALAYSIA' 'MEXICO' 'UNITED STATED'
 'SOUTH AFRICA' 'BELGIUM' 'NORTHERN IRELAND' 'SWEDEN' 'HONG KONG' 'KUWAIT'
 'NORWAY' 'SRI LANKA' 'USA VIRGIN ISLANDS' 'UNITED STATWS' 'ENGLANDUK'
 'UNITES STATES' 'ENGLAND UK' 'GREECE' 'JAPAN' 'U S' 'BRITAIN'
 'UNITED SATES' 'AUSTRIA' 'BRAZIL' 'CANADA OTTAWA ONTARIO' 'GLOBAL'
 'UNITED STATES OF AMERICAN' 'UNIITED STATES' 'UNITED KINGDOM ENGLAND'
 'WORLDWIDE BASED IN US BUT SHORT TERM TRIPS AROUDN THE WORLD' 'CANADW'
 'HUNGARY' 'LUXEMBOURG' 'UNITED SATES OF AMERICA'
 'UNITED STATES I WORK FROM HOME AND MY CLIENTS ARE ALL OVER THE USCANADAPR'
 'COLOMBIA' 'UNTED STATES' 'UNITED STATESP' 'UNITED STATTES'
 'UNITED STATEA' 'NEW ZEALAND' 'TRINIDAD AND TOBAGO' 'UNITED STATEES'
 'CAYMAN ISLANDS' 'CAN'
 'I AM LOCATED IN CANADA BUT I WORK FOR A COMPANY IN THE US'
 'UNIYED STATES' 'UNIYES STATES' 'UNITED STATES OF AMERICAS' 'UA'
 'CZECH REPUBLIC' 'CZECHIA' 'LATVIA' 'PUERTO RICO' 'US OF A' 'RWANDA'
 'UNITED ARAB EMIRATES' 'BANGLADESH' 'ROMANIA' 'UNITED KINDOM'
 'UNITED STATUS' 'SERBIA' 'PHILIPPINES' 'RUSSIA' 'POLAND' 'UXZ' 'TURKEY'
 'CANDA' 'CANADA AND USA' 'CATALONIA' 'ITALY SOUTH'
 'JERSEY CHANNEL ISLANDS' 'CHINA' 'VIRGINIA' 'AFGHANISTAN' 'ISRAEL' 'USS'
 'UNITEED STATES' 'NEW ZEALAND AOTEAROA' 'HARTFORD'
 'JAPAN US GOV POSITION' 'CSNADA' 'UNITED STARES' 'MAINLAND CHINA' 'IS'
 'UK NORTHERN IRELAND' 'UK FOR US COMPANY' 'NZ' 'TAIWAN' 'CANAD'
 'UNITE STATES' 'THE US' 'CAMBODIA' 'VIETNAM' 'REMOTE' 'SINGAPORE'
 'SOUTH KOREA' 'THAILAND' 'LITHUANIA' 'ERITREA' 'INDONESIA'
 'FOR THE UNITED STATES GOVERNMENT BUT POSTED OVERSEAS' 'UNITED KINGDOMK'
 'ITALY' 'CUBA' 'SLOVENIA' 'AUSTRALI' 'COTE DIVOIRE'
 'FROM ROMANIA BUT FOR AN US BASED COMPANY' 'SOMALIA'
 'WALES UNITED KINGDOM' 'ENGLAND GB' 'UNITEDSTATES' 'DANMARK'
 'UK NORTHERN ENGLAND' 'NL' 'NEDERLAND' 'SLOVAKIA' 'PORTUGAL'
 'ENGLAND UNITED KINGDOM' 'SIERRA LEONE' 'ENGLANG' 'UNITED STATEW' 'UAE'
 'INTERNATIONAL' 'THE BAHAMAS' 'WALES' 'COSTA RICA' 'UNITED STATUES'
 'UNTIED STATES' 'USA COMPANY IS BASED IN A US TERRITORY I WORK REMOTE'
 'CHILE' 'UK ENGLAND' 'UK REMOTE' 'SCOTLAND UK' 'USAB' 'UNITIED STATES'
 'QATAR' 'UNITED STTES' 'REMOTE PHILIPPINES' 'UNITES KINGDOM' 'NIGERIA'
 'PANAMÁ' 'AUSTRIA BUT I WORK REMOTELY FOR A DUTCHBRITISH COMPANY'
 'I WORK FOR AN US BASED COMPANY BUT IM FROM ARGENTINA' 'UNITER STATEZ'
 'CONGO' 'URUGUAY' 'PAKISTAN' 'BRASIL' 'USA TOMORROW' 'UNITED STATEDS'
 'NA REMOTE FROM WHEREVER I WANT'
 'US GOVT EMPLOYEE OVERSEAS COUNTRY WITHHELD' 'UGANDA' 'MALTA'
 'SAUDI ARABIA' 'BULGARIA' 'ESTONIA' 'MOROCCO' 'AFRICA' 'ECUADOR'
 'ZIMBABWE' 'GHANA' 'SAN FRANCISCO' 'USAT' '🇺🇸' 'LUXEMBURG'
 'UNITEF STATED' 'WALES UK' 'CROATIA' 'USAA' 'UKRAINE'
 'UNITED STATES PUERTO RICO'
 'FROM NEW ZEALAND BUT ON PROJECTS ACROSS APAC' 'Y' 'UNITED Y'
 'ISLE OF MAN' 'NORTHERN IRELAND UNITED KINGDOM' 'EUROPE' 'CALIFORNIA'
 'UK BUT FOR GLOBALLY FULLY REMOTE COMPANY' 'AUSTRALIAN' 'MÉXICO'
 'JAMAICA' 'USD' 'USA BUT FOR FOREIGN GOVT' 'KENYA' 'JORDAN'
 'UNITED STATSS' 'ARGENTINA BUT MY ORG IS IN THAILAND'
 'I WORK FOR A UAEBASED ORGANIZATION THOUGH I AM PERSONALLY IN THE US'
 'UNITED  STATES' 'AOTEAROA NEW ZEALAND' 'NA' 'POLICY' 'CYPRUS'
 'HONG KONH' 'UNITED STATES IS AMERICA' 'LIECHTENSTEIN'
 'COMPANY IN GERMANY I WORK FROM PAKISTAN' 'CANADÁ'
 'BOSNIA AND HERZEGOVINA']

In [32]:
#Mapping dictionary.
mapping = {
    'USA' : 'United States',
    'US' : 'United States',
    '🇺🇸' : 'United States',
    'ISA' : 'United States',
    'UNITED STATE' : 'United States',
    'AMERICA' : 'United States',
    'UNITED STATES OF AMERICA' : 'United States',
    'THE UNITED STATES' : 'United States',
    'UNITED STATE OF AMERICA' : 'United States',
    'UNITED STATED' : 'United States',
    'UNITED STATES' : 'United States',
    'USA VIRGIN ISLANDS' : 'United States',
    'UNITED STATWS' : 'United States',
    'UNITES STATES' : 'United States',
    'U S' : 'United States',
    'UNITED SATES' : 'United States',
    'UNITED STATES OF AMERICAN' : 'United States',
    'UIITED STATES' : 'United States',
    'WORLDWIDE BASED IN US BUT SHORT TERM TRIPS AROUDN THE WORLD' : 'United States',
    'UNITED SATES OF AMERICA' : 'United States',
    'UNITED STATES I WORK FROM HOME AND MY CLIENTS ARE ALL OVER THE USCANADAPR' : 'United States',
    'UNTED STATES' : 'United States',
    'UNITED STATESP' : 'United States',
    'UNITED STATTES' : 'United States',
    'UNITED STATEA' : 'United States',
    'UNITED STATEES' : 'United States',
    'UNIYED STATES' : 'United States',
    'UNIYES STATES' : 'United States',
    'UNITED STATES OF AMERICAS' : 'United States',
    'UNIITED STATES' : 'United States',
    'UA' : 'United States',
    'US OF A' : 'United States',
    'UNITED STATUS' : 'United States',
    'CANADA AND USA' : 'United States',
    'VIRGINIA' : 'United States',
    'USS' : 'United States',
    'UNITEED STATES' : 'United States',
    'UNITED STARES' : 'United States',
    'IS' : 'United States',
    'UNITE STATES' : 'United States',
    'THE US' : 'United States',
    'FOR THE UNITED STATES GOVERNMENT BUT POSTED OVERSEAS' : 'United States',
    'UNITEDSTATES' : 'United States',
    'UNITED STATEW' : 'United States',
    'UNITED STATUES' : 'United States',
    'UNTIED STATES' : 'United States',
    'USA COMPANY IS BASED IN A US TERRITORY I WORK REMOTE' : 'United States',
    'USAB' : 'United States',
    'UNITIED STATES' : 'United States',
    'UNITED STTES' : 'United States',
    'UNITER STATEZ' : 'United States',
    'USA TOMORROW' : 'United States',
    'UNITED STATEDS' : 'United States',
    'US GOVT EMPLOYEE OVERSEAS COUNTRY WITHHELD' : 'United States',
    'USAT' : 'United States',
    'UNITEF STATED' : 'United States',
    'USAA' : 'United States',
    'UNITED STATES PUERTO RICO' : 'United States',
    'UNITED Y' : 'United States',
    'USD' : 'United States',
    'USA BUT FOR FOREIGN GOVT' : 'United States',
    'UNITED STATSS' : 'United States',
    'I WORK FOR A UAEBASED ORGANIZATION THOUGH I AM PERSONALLY IN THE US' : 'United States',
    'UNITED  STATES' : 'United States',
    'UNITED STATES IS AMERICA' : 'United States',
    'HARTFORD' : 'United States',
    'UK' : 'United Kingdom',
    'UNITED KINGDOM' : 'United Kingdom',
    'UNITED KINDOM' : 'United Kingdom',
    'UK FOR US COMPANY' : 'United Kingdom',
    'UNITED KINGDOMK' : 'United Kingdom',
    'UK REMOTE' : 'United Kingdom',
    'UNITES KINGDOM' : 'United Kingdom',
    'UK BUT FOR GLOBALLY FULLY REMOTE COMPANY' : 'United Kingdom',
    'CANADA' : 'Canada',
    'CANADW' : 'Canada',
    'CAN' : 'Canada',
    'I AM LOCATED IN CANADA BUT I WORK FOR A COMPANY IN THE US' : 'Canada',
    'CANDA' : 'Canada',
    'CSNADA' : 'Canada',
    'CANAD' : 'Canada',
    'CANADÁ' : 'Canada',
    'CANADA OTTAWA ONTARIO' : 'Canada',
    'ENGLANDUK' : 'England',
    'ENGLAND UK' : 'England',
    'UNITED KINGDOM ENGLAND' : 'England',
    'ENGLAND GB' : 'England',
    'UK NORTHERN ENGLAND' : 'England',
    'ENGLAND UNITED KINGDOM' : 'England',
    'ENGLANG' : 'England',
    'UK ENGLAND' : 'England',
    'ENGLAND' : 'England',
    'SCOTLAND UK' : 'Scotland',
    'SCOTLAND' : 'Scotland',
    'THE NETHERLANDS' : 'Netherlands',
    'NETHERLANDS' : 'Netherlands',
    'NL' : 'Netherlands',
    'NEDERLAND' : 'Netherlands',
    'SAN FRANCISCO' : 'United States',
    'CALIFORNIA' : 'United States',
    'AUSTRALIA' : 'Australia',
    'AUSTRALI' : 'Australia',
    'AUSTRALIAN' : 'Australia',
    'ARGENTINA' : 'Argentina',
    'I WORK FOR AN US BASED COMPANY BUT IM FROM ARGENTINA' : 'Argentina',
    'ARGENTINA BUT MY ORG IS IN THAILAND' : 'Argentina',
    'MEXICO' : 'Mexico',
    'MÉXICO' : 'Mexico',
    'REMOTE' : 'Unknown',
    'NA' : 'Unknown',
    'Y' : 'Unknown',
    'NA REMOTE FROM WHEREVER I WANT' : 'Unknown',
    'INTERNATIONAL' : 'Unknown',
    'UXZ' : 'Unknown',
    'GLOBAL' : 'Unknown',
    'EUROPE' : 'Unknown',
    'AFRICA' : 'Unknown',
    'BRITAIN' : 'Great Britain',
    'GREAT BRITAIN' : 'Great Britain',
    'UAE' : 'United Arab Emirates',
    'FROM NEW ZEALAND BUT ON PROJECTS ACROSS APAC' : 'New Zealand',
    'NEW ZEALAND AOTEAROA' : 'New Zealand',
    'NZ' : 'New Zealand',
    'AOTEAROA NEW ZEALAND' : 'New Zealand',
    'JAPAN US GOV POSITION' : 'Japan',
    'CZECHIA' : 'Czech Republic',
    'COMPANY IN GERMANY I WORK FROM PAKISTAN' : 'Pakistan',
    'HONG KONH' : 'Hong Kong',
    'BRASIL' : 'Brazil',
    'UK NORTHERN IRELAND' : 'Northern Ireland',
    'NORTHERN IRELAND UNITED KINGDOM' : 'Northern Ireland',
    'WALES UK' : 'Wales',
    'WALES UNITED KINGDOM' : 'Wales',
    'AUSTRIA BUT I WORK REMOTELY FOR A DUTCHBRITISH COMPANY' : 'Austria',
    'FROM ROMANIA BUT FOR AN US BASED COMPANY' : 'Romania',
    'POLICY' : 'Canada',
    'PANAMÁ' : 'Panama',
    'MAINLAND CHINA' : 'China',
    'REMOTE PHILIPPINES' : 'Philippines',
    'ITALY SOUTH' : 'Italy',
}

In [33]:
#Using the mapping dictionary to replace the values currently in the "Country" column with the corresponding country name.
data.iloc[:, 10] = data.iloc[:, 10].replace(mapping)

In [34]:
#Change to uppercase for the first letter of each word.
data.iloc[:, 10] = data.iloc[:, 10] = data.iloc[:, 10].apply(lambda x: string.capwords(x))

In [35]:
#Final unique value list.
print(data.iloc[:, 10].unique())

['United States' 'United Kingdom' 'Canada' 'Scotland' 'Netherlands'
 'Australia' 'Spain' 'England' 'Finland' 'France' 'Germany' 'Ireland'
 'India' 'Argentina' 'Great Britain' 'Denmark' 'Switzerland' 'Bermuda'
 'Malaysia' 'Mexico' 'South Africa' 'Belgium' 'Northern Ireland' 'Sweden'
 'Hong Kong' 'Kuwait' 'Norway' 'Sri Lanka' 'Greece' 'Japan' 'Austria'
 'Brazil' 'Unknown' 'Hungary' 'Luxembourg' 'Colombia' 'New Zealand'
 'Trinidad And Tobago' 'Cayman Islands' 'Czech Republic' 'Latvia'
 'Puerto Rico' 'Rwanda' 'United Arab Emirates' 'Bangladesh' 'Romania'
 'Serbia' 'Philippines' 'Russia' 'Poland' 'Turkey' 'Catalonia' 'Italy'
 'Jersey Channel Islands' 'China' 'Afghanistan' 'Israel' 'Taiwan'
 'Cambodia' 'Vietnam' 'Singapore' 'South Korea' 'Thailand' 'Lithuania'
 'Eritrea' 'Indonesia' 'Cuba' 'Slovenia' 'Cote Divoire' 'Somalia' 'Wales'
 'Danmark' 'Slovakia' 'Portugal' 'Sierra Leone' 'The Bahamas' 'Costa Rica'
 'Chile' 'Qatar' 'Nigeria' 'Panama' 'Congo' 'Uruguay' 'Pakistan' 'Uganda'
 'Malta' 'Saudi Arabia' 'Bulgaria' 'Estonia' 'Morocco' 'Ecuador'
 'Zimbabwe' 'Ghana' 'Luxemburg' 'Croatia' 'Ukraine' 'Isle Of Man'
 'Jamaica' 'Kenya' 'Jordan' 'Cyprus' 'Liechtenstein'
 'Bosnia And Herzegovina']

In [36]:
#Unique values for "currency" column.
print(data.iloc[:, 7].unique())

['USD' 'GBP' 'CAD' 'EUR' 'AUD/NZD' 'Other' 'CHF' 'ZAR' 'SEK' 'HKD' 'JPY']

In [37]:
#Unique values for "other currency" column.
print(data.iloc[:, 8].unique())

[nan 'INR' 'Peso Argentino' '$76,302.34'
 'My bonus is based on performance up to 10% of salary'
 'I work for an online state university, managing admissions data. Not direct tech support. '
 '0' 'MYR' 'CHF' 'KWD' 'NOK' 'Na ' 'USD' 'BR$' 'SEK'
 'Base plus Commission ' 'canadian' 'Dkk' 'EUR' 'COP' 'TTD'
 'Indian rupees' 'BRL (R$)' 'Mexican pesos' 'CZK' 'GBP' 'DKK' 'Bdt'
 'RSU / equity' 'ZAR' 'Additonal = Bonus plus stock' 'American Dollars'
 'Php' 'PLN (Polish zloty)' 'Overtime (about 5 hours a week) and bonus'
 'czech crowns' 'Stock ' 'TRY' 'Norwegian kroner (NOK)' 'CNY' 'ILS/NIS'
 '55,000' 'AUD & NZD are not the same currency...' 'US Dollar' 'Canadian '
 'AUD' 'BRL' 'NIS (new Israeli shekel)' '-' 'RMB (chinese yuan)'
 'Taiwanese dollars'
 "AUD and NZD aren't the same currency, and have absolutely nothing to do with each other :("
 'NZD' 'Philippine Peso' 'SGD' 'KRW (Korean Won)' 'Czk' 'THB' 'IDR ' 'Sgd'
 'Nok' 'ILS (Shekel)' '6000 in stock grants annually' 'DKK ' 'China RMB'
 'AUD Australian ' 'LKR' 'Polish Złoty' 'Philippine peso (PHP)'
 'Australian Dollars ' 'PHP'
 'Many non-salary benefits - travel, free healthcare for self, very low for family, non-taxable housing allowance '
 'Equity'
 'It’s marketed as £22000 but we get paid pro-rats, so no pay for the school holidays.'
 'additional compensation is for overtime (i am paid hourly) so it varies. i have included an estimate'
 'ARS' 'Argentinian peso (ARS)' 'Israeli Shekels' 'ILS' 'MXN'
 'PhP (Philippine Peso)' 'Converted mine into USD for your easyness' 'PLN'
 'KRW' 'SAR' 'RM' 'IDR' 'None' 'Argentine Peso' 'Philippine Pesos' 'Ils'
 'Rs' 'INR (Indian Rupee)' 'NTD' 'Danish Kroner' 'CAD' 'Korean Won ' 'dkk'
 'Euro' 'SGD ' 'Mexican Pesos' 'THAI  BAHT'
 'Option to get 2x or 1.5x if taking on a weekend day in the summer'
 'Thai Baht ' '47000' 'na' 'Canadian' 'N/a' 'up to 12% annual bonus'
 'croatian kuna' 'PLN (Zwoty)' '5' 'Rupees' 'Singapore Dollara' 'NGN']

In [38]:
#Fixing data in the wrong column using the same technique as before.
row_index8 = data.loc[data.iloc[:, 8] == '$76,302.34'].index[0]

In [39]:
print(data.iloc[row_index8, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 11:14:29
How old are you?                                                                                                                                                                                                                                                                    45-54
What industry do you work in?                                                                                                                                                                                                                   Public Library (technically City Govt.?)
Job title                                                                                                                                                                                                                                                        Administrative Librarian
If your job title needs additional context, please clarify here:                                                                                                                                                                        I run a branch library and am responsible for ...
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               76,302
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                                 $76,302.34
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                                 Arizona
What city do you work in?                                                                                                                                                                                                                                                       Glendale
How many years of professional work experience do you have overall?                                                                                                                                                                                                         21 - 30 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                   21 - 30 years
What is your highest level of education completed?                                                                                                                                                                                                                        Master's degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 752, dtype: object

In [40]:
data.iloc[row_index8, 8] = 'NaN'

In [41]:
row_index9 = data.loc[data.iloc[:, 8] == 'My bonus is based on performance up to 10% of salary'].index[0]

In [42]:
print(data.iloc[row_index9, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 11:14:39
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                                           Recruitment or HR
Job title                                                                                                                                                                                                                                              Lead Payroll & Benefits Specialist
If your job title needs additional context, please clarify here:                                                                                                                                                                                                        No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               64,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                     6400.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                          My bonus is based on performance up to 10% of ...
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                                New York
What city do you work in?                                                                                                                                                                                                                                                     Schenectady
How many years of professional work experience do you have overall?                                                                                                                                                                                                             5-7 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                       5-7 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 766, dtype: object

In [43]:
data.iloc[row_index9, 9] = data.iloc[row_index9, 8]
data.iloc[row_index9, 8] = 'NaN'

In [44]:
row_index10 = data.loc[data.iloc[:, 8] == 'I work for an online state university, managing admissions data. Not direct tech support. '].index[0]

In [45]:
print(data.iloc[row_index10, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 11:14:45
How old are you?                                                                                                                                                                                                                                                                    45-54
What industry do you work in?                                                                                                                                                                                                                                Education (Higher Education)
Job title                                                                                                                                                                                                                                                        Sr Technical Support Rep
If your job title needs additional context, please clarify here:                                                                                                                                                                                                                       I
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               53,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                          I work for an online state university, managin...
If your income needs additional context, please provide it here:                                                                                                                                                                        I have excellent health benefits, time off, si...
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                              New Jersey
What city do you work in?                                                                                                                                                                                                                                                         Trenton
How many years of professional work experience do you have overall?                                                                                                                                                                                                          8 - 10 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                        Master's degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 776, dtype: object

In [46]:
data.iloc[row_index10, 8] = 'NaN'

In [47]:
row_index11 = data.loc[data.iloc[:, 8] == 'RSU / equity'].index[0]

In [48]:
print(data.iloc[row_index11, :])

Timestamp                                                                                                                                                                                                                                              4/27/2021 14:09:53
How old are you?                                                                                                                                                                                                                                                    35-44
What industry do you work in?                                                                                                                                                                                                                           Computing or Tech
Job title                                                                                                                                                                                                                                       Technical Program Manager
If your job title needs additional context, please clarify here:                                                                                                                                                                        Software engineer program manager
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                              151,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                    21000.0
Please indicate the currency                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                               RSU / equity
If your income needs additional context, please provide it here:                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                           Massachusetts
What city do you work in?                                                                                                                                                                                                                                          Boston
How many years of professional work experience do you have overall?                                                                                                                                                                                         11 - 20 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                   11 - 20 years
What is your highest level of education completed?                                                                                                                                                                                                        Master's degree
What is your gender?                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                         White
Name: 6802, dtype: object

In [49]:
data.iloc[row_index11, 9] = data.iloc[row_index11, 8]
data.iloc[row_index11, 8] = 'NaN'

In [50]:
row_index12 = data.loc[data.iloc[:, 8] == "AUD and NZD aren't the same currency, and have absolutely nothing to do with each other :("].index[0]

In [51]:
print(data.iloc[row_index12, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 21:47:39
How old are you?                                                                                                                                                                                                                                                                    35-44
What industry do you work in?                                                                                                                                                                                                                                           Computing or Tech
Job title                                                                                                                                                                                                                                                               software engineer
If your job title needs additional context, please clarify here:                                                                                                                                                                                                        No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                              120,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                      AUD/NZD
If "Other," please indicate the currency here:                                                                                                                                                                                          AUD and NZD aren't the same currency, and have...
If your income needs additional context, please provide it here:                                                                                                                                                                                                               Before tax
What country do you work in?                                                                                                                                                                                                                                                    Australia
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                            Not provided
What city do you work in?                                                                                                                                                                                                                                                       Melbourne
How many years of professional work experience do you have overall?                                                                                                                                                                                                          8 - 10 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                    8 - 10 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                  Man
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 10667, dtype: object

In [52]:
data.iloc[row_index12, 8] = 'NaN'

In [53]:
row_index13 = data.loc[data.iloc[:, 8] == 'Option to get 2x or 1.5x if taking on a weekend day in the summer'].index[0]

In [54]:
print(data.iloc[row_index13, :])

Timestamp                                                                                                                                                                                                                                                               5/8/2021 13:36:20
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                                                     Library
Job title                                                                                                                                                                                                                                                           Head of Teen Services
If your job title needs additional context, please clarify here:                                                                                                                                                                                                      Teen Librarian haha
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                                63000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                          Option to get 2x or 1.5x if taking on a weeken...
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                           Massachusetts
What city do you work in?                                                                                                                                                                                                                                                       Arlington
How many years of professional work experience do you have overall?                                                                                                                                                                                                             5-7 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                       5-7 years
What is your highest level of education completed?                                                                                                                                                                                                                        Master's degree
What is your gender?                                                                                                                                                                                                                                                           Non-binary
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 25795, dtype: object

In [55]:
data.iloc[row_index13, 9] = data.iloc[row_index13, 8]
data.iloc[row_index13, 8] = 'NaN'

In [56]:
row_index14 = data.loc[data.iloc[:, 8] == 'Many non-salary benefits - travel, free healthcare for self, very low for family, non-taxable housing allowance '].index[0]

In [57]:
print(data.iloc[row_index14, :])

Timestamp                                                                                                                                                                                                                                                              4/28/2021 14:25:40
How old are you?                                                                                                                                                                                                                                                                    45-54
What industry do you work in?                                                                                                                                                                                                                                                   Military
Job title                                                                                                                                                                                                                                                                       San Diego
If your job title needs additional context, please clarify here:                                                                                                                                                                                                                  Officer
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                              125,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                          Many non-salary benefits - travel, free health...
If your income needs additional context, please provide it here:                                                                                                                                                                              You are in a contract and can’t just quit.
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                      California, Oregon
What city do you work in?                                                                                                                                                                                                                                                       San Diego
How many years of professional work experience do you have overall?                                                                                                                                                                                                         21 - 30 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                   11 - 20 years
What is your highest level of education completed?                                                                                                                                                                                                                            High School
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 14331, dtype: object

In [58]:
data.iloc[row_index14, 9] = data.iloc[row_index14, 8]
data.iloc[row_index14, 8] = 'NaN'

In [59]:
row_index15 = data.loc[data.iloc[:, 8] == 'It’s marketed as £22000 but we get paid pro-rats, so no pay for the school holidays.'].index[0]

In [60]:
print(data.iloc[row_index15, :])

Timestamp                                                                                                                                                                                                                                                              4/28/2021 16:09:41
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                               Education (Primary/Secondary)
Job title                                                                                                                                                                                                                                                         SALT Teaching Assistant
If your job title needs additional context, please clarify here:                                                                                                                                                                                        Speech and Language specialist TA
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               19,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          GBP
If "Other," please indicate the currency here:                                                                                                                                                                                          It’s marketed as £22000 but we get paid pro-ra...
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                      England
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                            Not provided
What city do you work in?                                                                                                                                                                                                                                                 Sutton (Surrey)
How many years of professional work experience do you have overall?                                                                                                                                                                                                             5-7 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                        Master's degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 15065, dtype: object

In [61]:
data.iloc[row_index15, 9] = data.iloc[row_index15, 8]
data.iloc[row_index15, 8] = 'NaN'

In [62]:
row_index16 = data.loc[data.iloc[:, 8] == 'Additonal = Bonus plus stock'].index[0]

In [63]:
print(data.iloc[row_index16, :])

Timestamp                                                                                                                                                                                                                                              4/27/2021 14:35:27
How old are you?                                                                                                                                                                                                                                                    45-54
What industry do you work in?                                                                                                                                                                                                                           Computing or Tech
Job title                                                                                                                                                                                                                                              Content specialist
If your job title needs additional context, please clarify here:                                                                                                                                                                                        No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                               62,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                    17000.0
Please indicate the currency                                                                                                                                                                                                                                          EUR
If "Other," please indicate the currency here:                                                                                                                                                                                               Additonal = Bonus plus stock
If your income needs additional context, please provide it here:                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                      Ireland
If you're in the U.S., what state do you work in?                                                                                                                                                                                                            Not provided
What city do you work in?                                                                                                                                                                                                               Small country, prefer not to say!
How many years of professional work experience do you have overall?                                                                                                                                                                                         31 - 40 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                    8 - 10 years
What is your highest level of education completed?                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                         White
Name: 7233, dtype: object

In [64]:
data.iloc[row_index16, 9] = data.iloc[row_index16, 8]
data.iloc[row_index16, 8] = 'NaN'

In [65]:
row_index17 = data.loc[data.iloc[:, 8] == 'Base plus Commission '].index[0]

In [66]:
print(data.iloc[row_index17, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 11:59:26
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                                                       Sales
Job title                                                                                                                                                                                                                                                               Territory Manager
If your job title needs additional context, please clarify here:                                                                                                                                                                                   Software sales for automotive industry
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               33,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                      Base plus Commission
If your income needs additional context, please provide it here:                                                                                                                                                                        Commision checks every month that vary based o...
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                               Minnesota
What city do you work in?                                                                                                                                                                                                                                                          Duluth
How many years of professional work experience do you have overall?                                                                                                                                                                                                             5-7 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                  Man
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 3124, dtype: object

In [67]:
data.iloc[row_index17, 8] = 'NaN'

In [68]:
row_index18 = data.loc[data.iloc[:, 8] == 'Overtime (about 5 hours a week) and bonus'].index[0]

In [69]:
print(data.iloc[row_index18, :])

Timestamp                                                                                                                                                                                                                                                              4/27/2021 15:23:14
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                                           Computing or Tech
Job title                                                                                                                                                                                                                                                          Executive Assiatant II
If your job title needs additional context, please clarify here:                                                                                                                                                                                                                  Grade 6
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               86,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                    20000.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                  Overtime (about 5 hours a week) and bonus
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                           Massachusetts
What city do you work in?                                                                                                                                                                                                               HQ us in Cambridge, Ma but moving to the subur...
How many years of professional work experience do you have overall?                                                                                                                                                                                                             5-7 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 7915, dtype: object

In [70]:
data.iloc[row_index18, 9] = data.iloc[row_index18, 8]
data.iloc[row_index18, 8] = 'NaN'

In [71]:
row_index19 = data.loc[data.iloc[:, 8] == 'AUD & NZD are not the same currency...'].index[0]

In [72]:
print(data.iloc[row_index19, :])

Timestamp                                                                                                                                                                                                                                                   4/27/2021 17:50:21
How old are you?                                                                                                                                                                                                                                                         25-34
What industry do you work in?                                                                                                                                                                                                                     Engineering or Manufacturing
Job title                                                                                                                                                                                                                                                       Senior Analyst
If your job title needs additional context, please clarify here:                                                                                                                                                                                             No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                   108,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                             0.0
Please indicate the currency                                                                                                                                                                                                                                           AUD/NZD
If "Other," please indicate the currency here:                                                                                                                                                                                          AUD & NZD are not the same currency...
If your income needs additional context, please provide it here:                                                                                                                                                                                             No context needed
What country do you work in?                                                                                                                                                                                                                                         Australia
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                 Not provided
What city do you work in?                                                                                                                                                                                                                                            Melbourne
How many years of professional work experience do you have overall?                                                                                                                                                                                                  5-7 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                          2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                              College degree
What is your gender?                                                                                                                                                                                                                                                     Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                              White
Name: 9384, dtype: object

In [73]:
data.iloc[row_index19, 8] = 'NaN'

In [74]:
row_index20 = data.loc[data.iloc[:, 8] == '6000 in stock grants annually'].index[0]

In [75]:
print(data.iloc[row_index20, :])

Timestamp                                                                                                                                                                                                                                           4/28/2021 4:27:20
How old are you?                                                                                                                                                                                                                                                45-54
What industry do you work in?                                                                                                                                                                                                                  Transport or Logistics
Job title                                                                                                                                                                                                                                                  HR Manager
If your job title needs additional context, please clarify here:                                                                                                                                                                                    No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                          104,917
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                17000.0
Please indicate the currency                                                                                                                                                                                                                                      USD
If "Other," please indicate the currency here:                                                                                                                                                                                          6000 in stock grants annually
If your income needs additional context, please provide it here:                                                                                                                                                                                    No context needed
What country do you work in?                                                                                                                                                                                                                            United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                              Kansas
What city do you work in?                                                                                                                                                                                                                                      Tooeka
How many years of professional work experience do you have overall?                                                                                                                                                                                     21 - 30 years
How many years of professional work experience do you have in your field?                                                                                                                                                                               11 - 20 years
What is your highest level of education completed?                                                                                                                                                                                                    Master's degree
What is your gender?                                                                                                                                                                                                                                            Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                     White
Name: 11734, dtype: object

In [76]:
data.iloc[row_index20, 9] = data.iloc[row_index20, 8]
data.iloc[row_index20, 8] = 'NaN'

In [77]:
row_index21 = data.loc[data.iloc[:, 8] == 'up to 12% annual bonus'].index[0]

In [78]:
print(data.iloc[row_index21, :])

Timestamp                                                                                                                                                                                                                                                             10/26/2021 12:45:42
How old are you?                                                                                                                                                                                                                                                                    25-34
What industry do you work in?                                                                                                                                                                                                                                 Marketing, Advertising & PR
Job title                                                                                                                                                                                                                                                    Marketing Content Specialist
If your job title needs additional context, please clarify here:                                                                                                                                                                        Manage agencies that run video campaigns, prod...
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                                85000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                        0.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                     up to 12% annual bonus
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                                Missouri
What city do you work in?                                                                                                                                                                                                                                                       St. Louis
How many years of professional work experience do you have overall?                                                                                                                                                                                                             5-7 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                       5-7 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                                Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 27131, dtype: object

In [79]:
data.iloc[row_index21, 9] = data.iloc[row_index21, 8]
data.iloc[row_index21, 8] = 'NaN'

In [80]:
row_index22 = data.loc[data.iloc[:, 8] == 'additional compensation is for overtime (i am paid hourly) so it varies. i have included an estimate'].index[0]

In [81]:
print(data.iloc[row_index22, :])

Timestamp                                                                                                                                                                                                                                                              4/28/2021 17:33:28
How old are you?                                                                                                                                                                                                                                                                    18-24
What industry do you work in?                                                                                                                                                                                                                                Interior Design (commercial)
Job title                                                                                                                                                                                                                                                               Interior Designer
If your job title needs additional context, please clarify here:                                                                                                                                                                                                        No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                               40,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                     1200.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                          additional compensation is for overtime (i am ...
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                                 Georgia
What city do you work in?                                                                                                                                                                                                                                                         atlanta
How many years of professional work experience do you have overall?                                                                                                                                                                                                           2 - 4 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                         College degree
What is your gender?                                                                                                                                                                                                                                                           Non-binary
What is your race? (Choose all that apply.)                                                                                                                                                                                                                                         White
Name: 16139, dtype: object

In [82]:
data.iloc[row_index22, 9] = data.iloc[row_index22, 8]
data.iloc[row_index22, 8] = 'NaN'

In [83]:
row_index23 = data.loc[data.iloc[:, 8] == 'Converted mine into USD for your easyness'].index[0]

In [84]:
print(data.iloc[row_index23, :])

Timestamp                                                                                                                                                                                                                                                              4/28/2021 20:46:27
How old are you?                                                                                                                                                                                                                                                                    18-24
What industry do you work in?                                                                                                                                                                                                                                Education (Higher Education)
Job title                                                                                                                                                                                                                                                       Quality Assurance Auditor
If your job title needs additional context, please clarify here:                                                                                                                                                                                                        No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                                                2,400
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                                     1000.0
Please indicate the currency                                                                                                                                                                                                                                                          USD
If "Other," please indicate the currency here:                                                                                                                                                                                                  Converted mine into USD for your easyness
If your income needs additional context, please provide it here:                                                                                                                                                                                                        No context needed
What country do you work in?                                                                                                                                                                                                                                                     Pakistan
If you're in the U.S., what state do you work in?                                                                                                                                                                                                                            Not provided
What city do you work in?                                                                                                                                                                                                                                                         Karachi
How many years of professional work experience do you have overall?                                                                                                                                                                                                           2 - 4 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                                     2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                                           Some college
What is your gender?                                                                                                                                                                                                                                                                  Man
What is your race? (Choose all that apply.)                                                                                                                                                                                             Asian or Asian American, Another option not li...
Name: 17547, dtype: object

In [85]:
data.iloc[row_index23, 8] = 'NaN'

In [86]:
#Forcing upper case values and removing punctuation.
data.iloc[:, 8] = data.iloc[:, 8].str.upper()
data.iloc[:, 8] = data.iloc[:, 8].str.translate(str.maketrans('', '', string.punctuation))

In [87]:
#Trimming spaces after converting to strings.
data.iloc[:, 8] = data.iloc[:, 8].astype(str)
data.iloc[:, 8] = data.iloc[:, 8].apply(lambda x: x.strip())

In [88]:
#Found another value in the wrong column, fixed it here.
row_index24 = data.loc[data.iloc[:, 8] == 'STOCK'].index[0]

In [89]:
print(data.iloc[row_index24, :])

Timestamp                                                                                                                                                                                                                                             4/27/2021 15:28:25
How old are you?                                                                                                                                                                                                                                                   35-44
What industry do you work in?                                                                                                                                                                                                                          Computing or Tech
Job title                                                                                                                                                                                                                                    Senior Executive Assistant
If your job title needs additional context, please clarify here:                                                                                                                                                                                       No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                             115,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                                       0.0
Please indicate the currency                                                                                                                                                                                                                                         USD
If "Other," please indicate the currency here:                                                                                                                                                                                                                     STOCK
If your income needs additional context, please provide it here:                                                                                                                                                                                       No context needed
What country do you work in?                                                                                                                                                                                                                               United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                             Washington
What city do you work in?                                                                                                                                                                                                                                        Seattle
How many years of professional work experience do you have overall?                                                                                                                                                                                         8 - 10 years
How many years of professional work experience do you have in your field?                                                                                                                                                                                   8 - 10 years
What is your highest level of education completed?                                                                                                                                                                                                          Some college
What is your gender?                                                                                                                                                                                                                                               Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                             Native American or Alaska Native
Name: 8004, dtype: object

In [90]:
data.iloc[row_index24, 9] = data.iloc[row_index24, 8]
data.iloc[row_index24, 8] = np.nan

In [91]:
#Updated unique values for the "other currency" column. 
#I used this to keep track of how much I've done and what I still needed to fix.
print(data.iloc[:, 8].unique())

['nan' 'INR' 'PESO ARGENTINO' 'NAN' '0' 'MYR' 'CHF' 'KWD' 'NOK' 'NA' 'USD'
 'BR' 'SEK' 'CANADIAN' 'DKK' 'EUR' 'COP' 'TTD' 'INDIAN RUPEES' 'BRL R'
 'MEXICAN PESOS' 'CZK' 'GBP' 'BDT' 'ZAR' 'AMERICAN DOLLARS' 'PHP'
 'PLN POLISH ZLOTY' 'CZECH CROWNS' nan 'TRY' 'NORWEGIAN KRONER NOK' 'CNY'
 'ILSNIS' '55000' 'US DOLLAR' 'AUD' 'BRL' 'NIS NEW ISRAELI SHEKEL' ''
 'RMB CHINESE YUAN' 'TAIWANESE DOLLARS' 'NZD' 'PHILIPPINE PESO' 'SGD'
 'KRW KOREAN WON' 'THB' 'IDR' 'ILS SHEKEL' 'CHINA RMB' 'AUD AUSTRALIAN'
 'LKR' 'POLISH ZŁOTY' 'PHILIPPINE PESO PHP' 'AUSTRALIAN DOLLARS' 'EQUITY'
 'ARS' 'ARGENTINIAN PESO ARS' 'ISRAELI SHEKELS' 'ILS' 'MXN'
 'PHP PHILIPPINE PESO' 'PLN' 'KRW' 'SAR' 'RM' 'NONE' 'ARGENTINE PESO'
 'PHILIPPINE PESOS' 'RS' 'INR INDIAN RUPEE' 'NTD' 'DANISH KRONER' 'CAD'
 'KOREAN WON' 'EURO' 'THAI  BAHT' 'THAI BAHT' '47000' 'CROATIAN KUNA'
 'PLN ZWOTY' '5' 'RUPEES' 'SINGAPORE DOLLARA' 'NGN']

In [92]:
#Mapping dictionary for "Other currency" column.
mapping1 = {
    'nan' : np.nan,
    'NA' : np.nan,
    'NAN' : np.nan,
    '0' : np.nan, 
    '55000' : np.nan,
    '47000' : np.nan,
    '5' : np.nan,
    '' : np.nan,
    'NONE' : np.nan,
    'INDIAN RUPEES' : 'INR',
    'RUPEES' : 'INR',
    'INR INDIAN RUPEE' : 'INR',
    'PESO ARGENTINO' : 'ARS',
    'ARGENTINIAN PESO ARS' : 'ARS',
    'ARGENTINE PESO' : 'ARS',
    'CANADIAN' : 'CAD',
    'BRL R' : 'BRL',
    'BR' : 'BRL',
    'AMERICAN DOLLARS' : 'USD',
    'US DOLLAR' : 'USD',
    'MEXICAN PESOS' : 'MXN',
    'THAI BAHT' : 'THB',
    'THAI  BAHT' : 'THB',
    'PHILIPPINE PESO' : 'PHP',
    'PHILIPPINE PESO PHP' : 'PHP',
    'PHILIPPINE PESOS' : 'PHP',
    'PHP PHILIPPINE PESO' : 'PHP',
    'PLN POLISH ZLOTY' : 'PLN',
    'POLISH ZŁOTY' : 'PLN',
    'PLN ZWOTY' : 'PLN',
    'ILS SHEKEL' : 'ILS',
    'ILSNIS' : 'ILS',
    'NIS NEW ISRAELI SHEKEL' : 'ILS',
    'ISRAELI SHEKELS' : 'ILS',
    'CZECH CROWNS' : 'CZK',
    'KRW KOREAN WON' : 'KRW',
    'KOREAN WON' : 'KRW',
    'NORWEGIAN KRONER NOK' : 'NOK',
    'SINGAPORE DOLLARA' : 'SGD',
    'EURO' : 'EUR',
    'AUSTRALIAN DOLLARS' : 'AUD/NZD',
    'AUD AUSTRALIAN' : 'AUD/NZD',
    'AUD' : 'AUD/NZD',
    'NZD' : 'AUD/NZD',
    'CHINA RMB' : 'RMB',
    'RMB CHINESE YUAN' : 'RMB',
    'CNY' : 'RMB',
    'TAIWANESE DOLLARS' : 'TWD',
    'CROATIAN KUNA' : 'HRK',
    'RM' : 'MYR',
    'RS' : 'INR',
    'NTD' : 'TWD',
    'DANISH KRONER' : 'DKK',
}

In [93]:
#Same as the last time, this replaces the values in the "Other currency" column with the mapped values.
data.iloc[:, 8] = data.iloc[:, 8].replace(mapping1)

In [94]:
#Fixing another misplaced value.
row_index25 = data.loc[data.iloc[:, 8] == 'EQUITY'].index[0]

In [95]:
print(data.iloc[row_index25, :])

Timestamp                                                                                                                                                                                                                                        4/28/2021 15:43:39
How old are you?                                                                                                                                                                                                                                              25-34
What industry do you work in?                                                                                                                                                                                                           Marketing, Advertising & PR
Job title                                                                                                                                                                                                                                Marketing Content Creator
If your job title needs additional context, please clarify here:                                                                                                                                                                                  No context needed
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)                         65,000
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                                               5000.0
Please indicate the currency                                                                                                                                                                                                                                  Other
If "Other," please indicate the currency here:                                                                                                                                                                                                               EQUITY
If your income needs additional context, please provide it here:                                                                                                                                                                                  No context needed
What country do you work in?                                                                                                                                                                                                                          United States
If you're in the U.S., what state do you work in?                                                                                                                                                                                                          New York
What city do you work in?                                                                                                                                                                                                                                  Brooklyn
How many years of professional work experience do you have overall?                                                                                                                                                                                    8 - 10 years
How many years of professional work experience do you have in your field?                                                                                                                                                                               2 - 4 years
What is your highest level of education completed?                                                                                                                                                                                                   College degree
What is your gender?                                                                                                                                                                                                                                          Woman
What is your race? (Choose all that apply.)                                                                                                                                                                                                                   White
Name: 14915, dtype: object

In [96]:
data.iloc[row_index25, 9] = data.iloc[row_index25, 8]
data.iloc[row_index25, 8] = np.nan

In [97]:
#Replace "Other" values in the "Currency" column with the corresponding values in the "Other currency" column.
data.loc[data.iloc[:, 7] == 'Other', data.columns[7]] = data.iloc[:, 8]

In [98]:
#Unique values for "currency" column again, to check that previous code worked as intended.
print(data.iloc[:, 7].unique())

['USD' 'GBP' 'CAD' 'EUR' 'AUD/NZD' 'INR' 'ARS' 'CHF' 'MYR' 'ZAR' 'SEK'
 'HKD' 'NOK' 'BRL' 'DKK' 'TTD' 'MXN' 'CZK' 'BDT' 'PHP' 'PLN' 'TRY' 'RMB'
 'ILS' nan 'JPY' 'TWD' 'SGD' 'KRW' 'THB' 'IDR' 'LKR' 'SAR' 'HRK' 'NGN'
 'COP']

In [99]:
#Unique values for the yearly salary column.
unique_values = data.iloc[:, 5].unique()
for value in unique_values:
    print(value)

55,000
54,600
34,000
62,000
60,000
33,000
50,000
112,000
45,000
47,500
100,000
52,000
32,000
24,000
85,000
59,000
98,000
54,000
74,000
63,000
96,000
44,500
48,000
140,000
80,000
39,000
125,000
230,000
110,000
68,000
41,000
76,000
78,000
37,000
35,000
65,000
187,500
66,625
144,600
200,850
120,000
97,500
53,000
95,000
72,000
106,000
115,000
100,500
33,200
79,000
104,000
75,000
70,000
84,000
38,000
87,000
122,000
88,000
71,000
36,000
90,000
105,000
39,520
180,000
19,300
98,166
63,500
58
47,700
39,635
47,255
196,000
34,361
150,000
20,000
107,220
42,000
119,000
66,000
145,000
92,000
50,870
101,500
36,883
130,000
59,015
33,280
56,000
18,000
86,000
19,000
114,000
73,000
27,000
60,129
135,000
26,000
35
102,500
117,500
58,000
400,000
61,200
75,500
57,000
83,200
77,500
31,200
31,000
215,000
220,000
52,500
94,000
83,000
66,950
34,299
275,000
48,500
139,000
54,080
170,000
82,160
25,700
77,000
25,217
31,616
31,500
165,000
45,760
78,240
23,050
67,000
190,000
60,320
49,000
28,000
40,575
29,000
61,000
47,250
260,000
78,167
132,500
124,000
108,000
91,000
117,000
71,697
61,500
47,840
109,000
40,613
32,640
17,000
64,000
114,400
111,500
58,300
700,000
156,000
126,000
38,480
53,500
49,600
57,750
43,680
103,000
51,000
25,000
93,000
34,500
72,500
179,000
64,200
43,500
87,938
186,000
61,800
155,000
40,000
71,750
157,000
42,120
175,000
134,000
98,500
43,000
36,712
71,500
146,000
131,000
38,800
107,000
600,000
82,000
885,000
157,029
83,500
58,240
107,500
82,400
82,500
201,000
210,000
58,800
101,360
66,805
134,800
38,600
102,000
136,000
72,100
37,024
64,800
70,600
44,290
39,917
59,400
54,075
53,895
67,080
71,400
103,500
38,110
32,033
37,500
60,500
89,000
78,400
118,000
153,000
66,900
44,777
110,400
200,000
69,000
94,257
72,300
97,000
44,000
111,433
58,327
144,000
66,840
35,140
1,080,000
154,000
37,960
67,150
65,252
37,440
142,335
23,000
37,419
21,912
52,800
25,450
87,550
46,000
57,500
127,500
93,600
66,913
78,280
87,360
81,000
58,500
241,000
68,245
56,500
53,040
65,818
133,540
39,500
89,024
59,500
113,000
26,500
60,800
33,800
49,524
176,500
81,200
52,520
160,000
253,300
66,250
250,000
71,309
67,675
101,000
222,000
64,625
160,367
76,302
40,460
128,000
145,600
178,000
73,495
300,000
46,100
62,700
24,461
93,689
69,500
47,000
55,600
87,500
68,150
151,000
110,500
43,607
59,800
81,120
72,800
41,470
158,000
76,100
86,100
71,800
36,600
35,400
56,271
41,787
50,821
65,520
168,000
35,360
38
146,220
98,765
68,800
132,860
27,300
89,980
114,059
40,206
185,000
49,500
52,125
128,203
57,879
42,400
35,100
65,936
55,785
62,500
212,000
61
111,360
116,000
93,800
64,854
82,650
100,962
51,796
390,000
140,400
32,500
54,500
95,325
188,000
47,902
4,400
350,000
27,289
32,448
48,410
74,200
122,540
75,603
48,925
58,303
58,195
118,360
65,100
88,400
46,300
78,998
58,344
18,720
77,230
16,000
65,364
88,700
67,500
74,100
44,750
38,251
171,912
76,250
72,450
30,000
35,500
48,700
92,500
39,017
48,464
66,300
54,599
183,600
27,946
12,000
73,700
40,800
33,900
151,374
91,155
94,896
45,700
167,000
53,800
68,392
94,350
40,500
132,100
116,513
225,000
46,500
114,885
45,271
173,325
40,116
70,720
80,718
88,200
126,500
76,475
86,662
80,640
147,240
55,500
59,699
22,000
36,599
38,500
104,500
149,000
96,512
99,000
62,608
148,000
76,500
40,007
62,600
38,727
75,950
77,300
62,672
95,600
42,500
121,000
112,500
103,690
107,900
1,150,000
85,116
65,339
66,990
54,389
84,300
33,500
77,250
34,840
78,500
65,949
41,394
58,350
107,146
36,500
113,400
31,170
91,500
70,662
143,520
93,583
31,824
64,500
36,200
183,000
66,820
216,000
223,000
214,000
100,300
86,700
39,140
73,500
172,000
130
38,200
142,000
54,953
48,609
46,145
50,160
87,400
51,350
64,105
51,500
135,200
44,553
75,544
450,000
47,612
65,790
68,300
65,500
138,000
121,184
147,000
84,578
137,280
83,720
70,800
56,160
28,600
44,300
36,400
42,900
124,800
62,400
32,350
64,304
51,140
38,792
14,500
74,568
159,600
44,394
96,900
42,640
106,080
66,376
129,000
105,456
74,607
66,705
57,360
396,000
92,068
193,000
80,700
11,000
342,000
41,100
40,602
36,050
21,500
76,900
36,663
132,000
832,000
102,550
13,560
49,050
48,355
45,500
800,000
20,287
118,450
125,300
83,942
82,850
74,400
92,700
52,650
74,651
65,332
56,394
57,845
23,541
106,433
77,800
123,000
44,096
12,500
75,600
669,500
55,156
72,775
45,900
21,179
44,755
127,553
101,024
42,972
22,256
27,500
33,700
118,560
63,595
3,000,000
127,000
77,200
86,132
74,885
42,750
131,100
77,922
46,800
27,950
21,000
119,915
162,760
57,636
84,500
91,355
33
55,900
25,481
63,420
70,040
59,600
25,300
82,200
42,078
56,400
146,500
30,300
52,740
53,863
47,076
45,750
81,600
133,452
43,550
41,800
58,900
246,000
64,906
63,600
87,304
143,000
51,600
70,400
50,800
116,802
100,100
43,696
44,335
54,250
72,700
123,250
69,470
68,500
46,698
66,703
122,577
49,005
41,600
48,068
40,040
54,511
20,137
41,043
23,067
50,148
72,467
114,050
45,654
101,441
55,450
66,189
29,473
48,807
29,600
30,414
54,700
625,000
37,400
116,715
50,003
64,272
90,762
149,865
41,017
100,940
135,400
103,600
85,200
39,600
116,400
38,760
199,900
33,176
149,160
560,000
49,100
144,128
47,195
87,060
74,618
57,340
42,432
57,712
114,500
78,542
91,160
54,723
38,017
56,238
22,657
82,700
44,341
170,500
66,500
93,415
61,032
152,000
57,288
48,205
32,400
61,710
215,358
42,723
65,557
320,000
53,955
67,800
118,392
49,920
67,224
408,000
84,562
111,000
64,890
110,900
185,700
360,000
89,500
96,600
97,072
55,786
18,500
205,000
160,500
114,240
55,300
18,642
543,000
44,780
61,734
149,500
70,700
43,875
240,000
159,120
780,000
51,979
31,422
42,827
43,187
43,560
88,649
39,666
66,040
23,700
152,169
86,720
318,000
79,600
98,300
68,250
125,500
58,363
78,346
17,550
162,000
124,155
61,825
55,800
86,800
81,100
17,200
64,100
58,697
27,040
47,999
31,366
63,939
40,700
23,337
117,875
65,920
47,600
75,725
1,400,000
103,271
83,262
94,640
100,597
58,510
133,000
73,405
53,310
180,600
54,313
90,100
53,066
68,600
173,000
48,929
132,600
45,480
89,440
380,000
182,245
61,125
31,435
78,612
100,050
119,600
39,277
39,300
51,454
29,120
280,000
312,500
38,300
84,900
26,250
52,100
59,527
21,800
504,000
51,847
59,826
97,760
67,231
113,600
59,750
51,820
47,094
23,920
56,999
657,900
20,800
51,750
52,275
76,668
13,520
101,985
54,540
64,575
128,125
56,850
114,373
34,859
29,808
25,500
45,360
55,703
138,500
101,050
110,603
34,444
206,000
46,700
79,023
80,800
77,776
30,900
62,800
44,345
96,500
74,020
77,269
33,508
92,781
102,000,000
97,395
229,500
102,545
123,746
47,736
78,650
121,800
29,660
106,193
109,700
33,150
88,500
154,500
65,409
575,000
68,195
113,150
44,226
78,800
90,580
49,377
60,900
60,180
235,000
69,422
65,620
31,776
36,364
199,990
265,000
255,000
77,625
174,000
72,855
137,770
73,300
100,200
166,000
26,350
64,671
4,000
134,125
48,300
84,176
50,500
51,475
66,285
134,971
40,709
68,640
57,766
38,083
73,170
56,860
77,400
312,000
63,550
54,878
63,375
57,383
79,500
38,237
13,000
127,885
94,500
57,678
57,200
67,600
51,001
70,270
27,565
141,500
108
56,403
199,000
42,182
71,900
68,560
22,500
100,800
87,090
95,900
19,797
40,300
58,750
1,100,000
50,066
59,426
163,000
41,500
102,924
86,400
48,028
85,700
37,796
35,600
70,210
208,000
31,180
125,819
41,540
195,000
146,438
37,107
76,485
80,964
134,500
73,308
54,285
52,332
61,442
70,135
141,000
15,000
37,502
130,700
75,420
91,200
158,160
40,400
54,329
27,030
90,119
43,939
41,200
38,875
132,800
60,171
62,172
171,000
67,900
94,400
76,750
57,400
99,221
46,895
2,800,000
266,250
71,514
112,016
58,657
49,089
63
47,761
104,600
51,330
61,589
70,010
28,333
57,900
87,900
89,800
70,291
69,100
87,700
172,500
20,019
32,760
244,000
47,205
78,144
78,640
79,900
108,518
34,808
65,386
152,630
142,950
43,800
56,846
46,467
137,000
30,238
64,341
47,942
37,398
41,766
61,568
90,396
36,100
72,633
81,950
58,212
94,700
310,000
89,312
87,274
39,400
70,500
38,257
161,200
74,500
58,075
14,000
29,640
48,062
65,547
162,400
107,300
138,800
76,997
50,212
100,006
97,200
112,200
49,900
122,416
534,300
181,000
83,175
109,366
159,000
198,000
48,790
30,992
35,570
68,850
61,854
131,950
13,300
58,762
70,200
70,019
67,250
80,145
130,800
44,200
100,796
23,750
94,120
40,200
87,200
118
38,784
64,260
211,000
30,264
45,281
141,900
82,344
89,300
46,010
40
52,490
73,986
340,000
253,000
113,300
100,400
105,426
77,443
29,160
65,300
30,680
183,700
540,000
73,330
1,200,000
94,550
47,200
39,998
245,000
63,300
33,050
54,800
215,250
43,264
53,560
50,271
86,500
84,072
77,293
65,205
120,640
63,960
62,618
38,890
35,265
70,451
91,276
68,700
71,488
40,560
115,500
136,843
46,758
59,280
88,250
122,709
93,328
71,250
76,350
109,691
41,641
41,204
74,997
118,937
16,500
93,500
200,500
68,556
87,250
23,100
46,400
98,908
83,622
79,251
131,500
910,000
72,592
41,050
86,300
131,600
34,400
72,612
24,500
20,250
24,900
173,500
34,320
98,200
202,000
113,500
38,844
95,200
69,348
121,500
48,880
59,700
78,999
66,681
69,004
56,640
126,600
120,700
78,600
217,000
101,895
813,000
12,060
1,900,000
79,626
48,195
86,953
81,700
66,650
68,900
66,100
20,488
46,280
140,500
52,400
75,795
152,900
30,500
109,500
45,400
55,120
18
82,125
31,600
81,500
71,600
79,950
128,530
39,990
135,600
175,625
63,400
151,800
128,400
79,040
28,080
42,224
66,127
99,600
35,211
139,458
51,333
38,688
176,000
29,998
63,750
122,530
51,079
118,500
72,548
24,980
29,078
49,008
55,620
213,200
36,421
91,520
70
47,739
56,100
45,520
10,000
27,770
88,800
64,446
71,077
73,080
56,800
60,777
76,147
62,150
84,200
77,488
83,300
70,584
32,240
58,493
60,206
75,552
36,088
56,250
105,240
77,830
50
120,864
81,291
34,216
69,700
87,100
111,783
52,600
69,665
99,500
329,000
126,282
45,600
54,350
32,562
84,884
85,600
49,200
28,331
57,869
61,400
117,792
75,900
46,040
41,350
100,440
53,600
62,860
365,000
71,760
103,736
86,408
155
57,800
61,152
84,670
107,250
86,665
72,630
152,350
204,000
64,750
75,705
56,280
76,989
39,800
410,000
23,500
31,075
101,100
45,204
79,880
66,089
17,680
55,467
56,200
89,670
47,685
91,533
48,600
181,290
75,972
50,300
845,000
62,488
750,000
144,991
1,650,000
61,157
31,678
97,646
115,600
108,055
62,084
73,880
98,486
72,587
85,283
71,734
117,851
68,215
80,673
63,189
50,200
85,280
96,200
83,385
66,800
114,725
552,000
52
89,025
144,500
82,800
179,667
18,005
48,963
734,400
288,000
45,260
71,660
6,400
194,000
95,663
133,510
133,314
43,850
41,318
114,300
62,480
61,131
88,618
25,100
22,750
133,500
75,920
47,362
50,450
73,647
106,137
54,877
164,000
32,280
34,614
23,850
35,370
80,636
86,881
67,526
103,842
72,750
77,586
74,880
31,594
60,200
98,600
33,300
105,500
42,600
438,000
47,008
19,978
63,524
83,350
78,786
11,400
974,400
51,226
22,880
123,500
87,445
18,532
84,975
89,975
53,361
114,900
60,965
136,500
49,331
65,668
106,733
91,914
39,129
54,538
109,450
66,463
187,000
94,710
53,539
61,089
40,798
32,408
38,400
87,490
59,874
86,382
33,600
550,000
38,700
74,803
23,400
510,000
264
134,318
58,572
75,660
52,174
226,000
168,150
71,177
50,900
29,200
31,657
88,007
63,826
96,428
60,130
29,470
37,544
90,656
35,790
54,200
34,800
22,417
20,400
104,769
94,100
285,248
64,480
82,655
31,831
87,220
55,550
46,165
56,550
47,817
29,702
81,916
38,835
83,154
51,088
500,000
31,408
27,600
50,675
62,940
315,000
67,670
33,320
75,300
42,300
36,920
53,024
35,208
88,077
24,960
54,370
78,260
45,009
30,368
77,905
33,384
227,115
77,112
73,452
26,400
105,109
44,740
40,894
76,960
196,800
34,900
50,443
37,840
207,000
50,575
23,665
122,500
62,423
75,212
72
39,632
123,050
108,150
135,987
31,680
56,409
55,680
109,769
71,350
76,200
41,447
148,500
22,400
72,613
432,000
292,000
95,838
47,258
65,083
169,000
36,720
95,253
60,990
93,750
63,654
43,974
28,500
70,980
66,105
29,250
34,709
36,962
44,800
67,400
112,562
103,550
8,000
104,200
58,448
86,625
89,600
92,091
60,700
14,400
69,355
75,400
52,776
97,800
68,304
62,350
61,700
58,650
55,232
64,197
38,660
32,552
52,903
17,076
181,500
77,600
586,500
75,700
91,750
50,544
77,895
71,711
91,044
68,958
25,480
49,982
40,881
62,129
100,726
44,850
52,532
40,880
106,600
65,188
48,230
151,810
100
46,725
81,473
99,250
75,608
40,768
52,200
62,364
83,400
73,236
60,350
91
64,338
99,400
35,172
75,867
58,710
53,461
35,028
81,300
0
80,300
21,879
85,500
42,140
364,000
129,316
155,800
80
77,501
182,000
52,665
81,391
49,750
93,132
118,268
45,450
70,100
57,250
51,300
127,800
73,611
93,013
134,782
55,086
55,862
68,124
35,350
65,163
70,288
1
108,160
66,851
51,200
52,386
71,700
57,700
52,798
48,850
75,100
35,880
40,322
829,500
41,912
34,140
138,100
168,900
69,920
116,584
83,496
32,676
27,012
74,155
184,000
16,653
116,300
17,280
72,400
28,200
43,944
97,232
1,334,782
192,000
36,700
80,500
88,600
93,536
61,767
55
120,660
110,824
126,200
26,600
78,078
90,500
79,999
67,100
108,870
61,567
13,600
51,800
232,000
48,800
78,404
13,400
207,500
79,612
264,000
95,500
58,635
136,240
83,940
65,880
50,100
104,640
130,704
46,125
41,428
51,251
76,800
53,400
98,650
117,700
305,000
44,450
95,850
121,129
45,250
63,319
90,351
92,580
49,275
78,560
20,300
30,160
57,985
111,900
97,152
80,881
51,400
126,300
21,840
85,800
148,650
105
161,000
107,670
87,962
91,444
91,811
176,800
62,140
90,938
45,800
36,075
63,864
159,677
103,516
103,630
90,410
66,850
90,848
92,600
91,929
435,000
53,045
19,880
62,593
91,800
51,490
31,262
96,285
78,624
49,330
83,250
84,279
105,600
60,570
50,689
57,312
138,400
42,800
38,100
157,604
62,300
38,563
65
90,280
55,182
4,600,000
113,235
47,940
61,529
63,661
77,100
46,750
59,900
80,160
27,288
177,000
75,712
8,100,000
6,000,000
56,700
46,813
95,860
105,300
28,604
43,580
4,800,000
74,600
106,840
81,400
142,100
120,910
60
64,700
31,700
102,028
732,000
139,500
44,720
161,730
117,516
37,008
283,000
133,151
76,968
60,667
31,702
56,405
18,137
238,000
77,459
34,112
79,375
38,105
249,410
96,800
86,520
155,375
27,070
73,320
11,500,000
133,537
425,000
26,168
54,739
156,600
69,888
97,129
83,600
52,260
94,300
55,200
149,074
33,680
45,300
370,000
119,200
113,105
143,100
57
94,010
63,590
99,750
88,434
168,200
47,507
179,301
45,150
68,652
43,642
182,500
76,405
62,900
203,000
78,250
170,100
226,800
2,100,000
69,870
56,364
123,600
221,000
69,886
53,680
270,000
206,500
21,600
78,894
197,000
43,980
40,320
166,400
116,500
107,604
90
12,600
99,840
96,608
66,560
66,050
50,600
44,400
117,800
27,000,000
37,700
117,520
88,586
6,600
84,400
56,062
77,480
20,200
132,999
525,000
720,000
28,335
50,960
55,744
78,408
5,600,000
268,000
93,662
64,400
114,100
124,896
3,225,000
52,550
14,700
97,282
147,500
870,000,000
91,422
100,360
62,100
107,600
61,838
115,400
88,895
54,100
82,100
74,554
78,900
414,000
189,000
85,850
77,924
840,000
58,535
75,779
660,000
88,750
620,000
61,100
556,200
30,046
875,000
21,247
125,400
99,800
43,950
57,600
96,700
27,142
40,100
276,000
21,325
191,513
41,303
40,095
61,577
33,234
32,817
1,324,000
112,818
27,700
9,600
51,250
30,877
187,200
40,414
16,251
104,917
457,000
440,000
17,400
39,890
22,200
34,050
274,000
93,900
50,768
30,950
41,450
26,700
30,090
57,533
26,116
36,027
40,890
37,140
406,800
27,250
33,143
33,689
37,333
51,435
25,941
233,160
55,100
2,500,000
30
295,000
62,540
61,600
22,330
49,088
24,907
83,408
30,150
87,318
56,295
98,800
53
117,400
82,740
2,200
29,388
25,788
75,140
68,680
57,324
49,250
76,962
15,400
49,704
49,800
51,726
50,752
42,426
57,740
23,010
90,106
53,125
64,147
690,000
52,685
74,482
57,969
74,446
130,698
50,424
53,670
170,600
55,700
20,600
50,400
70,470
63,140
21,200
88,560
79,800
64,325
42,130
205,500
112,320
61,750
46,976
126,614
59,665
17,300
72,578
145,200
60,680
36,800
5,700
40,251
69,219
76,522
74,793
56,660
74,450
52,700
83,475
41,750
43,700
91,794
235,186
43,695
46,347
91,900
73,548
369,000
375,000
82,702
41,250
77,555
49,990
45,726
78,540
56,600
82,550
86,659
119,500
136,834
57,160
99,364
89,750
483,600
72,557
37,877
162,900
48,763
73,542
40,600
114,592
97,039
20,500
75,619
44,948
45,166
53,530
103,586
82,060
51,294
88,272
33,580
41,638
46,170
70,850
26,421
2,400
36
88,622
25,881
905,000
45,801
100,825
46,175
48,818
62,616
117,600
101,200
104,312
64,790
126,736
24,252
24,560
46,613
106,469
44,100
38,833
41,392
56,650
71,989
21,142
29,725
68,647
34,715
113,362
49,149
67,558
40,367
38,404
76,162
60,121
111,192
152,800
73,185
46,865
62,691
29,150
102,200
58,600
134,129
50,614
70,738
42,161
74,222
148,274
64,300
40,520
24,100
257,000
78,980
28,735
36,028
59,195
93,203
107,705
98,950
62,572
141,440
116,358
172,700
114,700
32,800
140,845
46,561
142,800
38,975
19,583
53,352
70,054
64,834
91,112
46,183
16,640
444,000
52,020
137,500
58,784
95,300
67,650
180,200
67,275
92,435
67,550
60,108
58,864
47,800
48,750
80,111
47,097
75,114
119,820
30,200
63,240
73,600
162,390
119,900
317,000
26,100
71,958
34,190
97,375
38,188
72,858
53,250
88,100
82,275
37,814
804,000
54
73,216
68,806
40,102
98,736
126,684
290,000
30,220
60,125
36,550
72,600
28,850
614,000
68,723
48,070
106,500
77,725
141,520
15,100
58,400
76,073
35,750
123,800
67,110
279,000
42,840
109,270
98,714
66,617
39,975
42,848
51,588
69,360
81,863
78,728
74,900
45,427
65,900
63,638
80,683
37,926
59,300
16,800
89,612
689,000
3,200
47,216
116,700
47,425
78,292
83,260
520,000
32,900
68,685
66,599
90,909
99,745
25,012
48,900
43,775
43,992
950,000
39,820
49,831
149,660
50,876
91,700
121,200
110,269
49,120
456,000
57,211
92,352
37
92,075
62,880
42,286
92,900
191,000
228,000
82,181
180,500
93,198
69,624
2,300,000
77,900
44,237
37,731
285,000
101,759
36,953
69,241
850,000
26,587
70,087
79,285
148,750
35,054
40,997
835,000
111,100
60,100
65,600
80,038
42,016
28,152
59,780
93,777
45,506
43,212
49,494
72,480
87,552
70,725
504,456
88,580
132,840
51,272
53,248
52,606
97,125
53,950
64,900
99,945
39,936
64,215
37,638
135,283
49,350
40,830
103,996
38,313
40,050
10,500
95,250
133,600
101,900
37,200
123,178
28,800
66,844
77,350
63,860
144,800
92,143
87,428
78,277
61,360
178,400
19,671
13,500
99,700
40,261
94,800
58,760
89,344
131,690
102
79,719
32,073
96,262
367,500
55,224
52,320
55,214
89,900
105,723
133,400
117,120
182,450
58,320
65,166
50,211
90,600
73,645
75,078
69,600
38,040
27,248
97,365
69,800
51,584
83,900
90,960
74,800
29,500
122,595
56,784
106,800
89,470
22,800
92,035
80,250
2,111,538
805,000
72,399
155,202
72,200
86,810
54,184
5,427
44,298
171,500
42,200
77,022
103,980
45,115
80,891
46,275
70,452
81,900
36,316
82,404
105,060
63,898
85,550
75,945
50,073
43,678
7,390
42,240
28
139,461
18,200
89,401
3,600,000
124,600
80,164
19,100
100,260
129,851
82,908
103,200
91,605
31,150
31,257
121,600
47,415
240
106,742
67,700
37,250
30,475
38,230
49,400
129,260
166,560
41,288
61,900
69,613
335,000
121,360
85,400
109,236
44,784
29,995
24,321
32,656
116,208
59,955
192,400
37,850
39,995
124,750
58,700
20,675
58,398
237,000
61,392
63,700
165,450
37,954
25,097
89,170
87,197
46,006
59,200
62,727
567,600
109,200
162,800
15,080
96,357
86,796
24,600
76,050
512,000
93,200
82,891
29,930
234,000
96,820
62,271
127,688
47,445
31,999
19,380
164,800
169,180
45,050
36,812
114,350
249,000
47,320
117,300
19,500
36,420
60,156
76,361
87,198
57,026
41,206
580,000
54,337
69,680
79,609
51,150
70,560
93,300
74,825
30,420
350
145,500
71,933
102,645
112,800
41,925
99,100
82,680
34,944
45,991
59,987
43,860
48,980
19,885
858,000
101,209
82,600
23,150
50,595
48,851
1,442
1,300,000
96,400
56,410
90,744
136,716
159,850
430,000
124,564
15,600
570,000
101,250
100,880
144,200
402,000
43,591
49,487
58,260
130,680
75,499
77,077
152,182
146,536
47,946
142,700
152,300
69,659
59,044
325,000
231,000
194,500
82,075
71,194
41,520
122,750
87,300
31,900
603,000
53,923
60,140
31,300
130,660
111,340
130,893
134,708
175,454
79,890
168,067
77,668
100,700
287,000
191,500
87,010
89,700
111,200
68,220
53,274
480,000
149,600
33,534
42,819
56,997
124,428
90,300
107,100
84,448
420,000
284,000
62,088
1,260,000
73,599
37,114
46,200
120,365
378,000
170,400
79,132
59,040
475,000
415,000
144,656
44,714
66,520
54,325
40,054
7,250
41,556
43,035
119,700
79,560
49,700
160,800
97,835
194,150
69,300
49,060
108,500
77,069
145,689
60,650
86,200
106,808
165,500
89,380
243,000
121,139
8,800,000
64,844
119,392
31,400
11,100
32,300
267,500
151,300
145,610
219,000
71,944
110,800
9,000
51,450
5,265
55,240
110,700
64,600
72,250
28,536
242,500
156,832
91,243
58,950
157,400
28,100
250,600
630,000
150,500
38,000,000
85,300
86,158
197,600
67,200
243,200
139,050
62,286
868,000

In [100]:
#Convert all values to numeric values after removing commas.
data.iloc[:, 5] = data.iloc[:, 5].str.replace(',', '')
data.iloc[:, 5] = pd.to_numeric(data.iloc[:, 5], errors='coerce')

In [101]:
#Some values for salary are not including the 1000s so anything 3 digits or less gets multiplied by 1000.
for i, value in enumerate(data.iloc[:, 5]):
    if pd.notna(value) and value <= 999:
        data.at[i, data.columns[5]] = value * 1000

In [102]:
#Changing the "Timestamp" column to ISO 8601 format.
data['Timestamp'] = pd.to_datetime(data['Timestamp'], format='%m/%d/%Y %H:%M:%S')

In [103]:
#Final visual inspection indicates that this data is now ready for use.
#For data storage, column names will need to be changed to be shorter. 
#Use of string search functions will suffice for the "Job title" column, as the values have too much variation to standardize.
data.head(50)

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,2021-04-27 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,No context needed,55000,0.0,USD,NaN,No context needed,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,2021-04-27 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,No context needed,54600,4000.0,GBP,NaN,No context needed,United Kingdom,Not provided,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,2021-04-27 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,No context needed,34000,0.0,USD,NaN,No context needed,United States,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,2021-04-27 11:02:41,25-34,Nonprofits,Program Manager,No context needed,62000,3000.0,USD,NaN,No context needed,United States,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,2021-04-27 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,No context needed,60000,7000.0,USD,NaN,No context needed,United States,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
5,2021-04-27 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,No context needed,62000,0.0,USD,NaN,No context needed,United States,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
6,2021-04-27 11:02:51,25-34,Publishing,Publishing Assistant,No context needed,33000,2000.0,USD,NaN,No context needed,United States,South Carolina,Columbia,2 - 4 years,2 - 4 years,College degree,Woman,White
7,2021-04-27 11:03:00,25-34,Education (Primary/Secondary),Librarian,"High school, FT",50000,0.0,USD,NaN,No context needed,United States,Arizona,Yuma,5-7 years,5-7 years,Master's degree,Man,White
8,2021-04-27 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,112000,10000.0,USD,NaN,No context needed,United States,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
9,2021-04-27 11:03:02,35-44,"Accounting, Banking & Finance",Senior Accountant,No context needed,45000,0.0,USD,NaN,I work for a Charter School,United States,Florida,Palm Coast,21 - 30 years,21 - 30 years,College degree,Woman,"Hispanic, Latino, or Spanish origin, White"
10,2021-04-27 11:03:03,25-34,Nonprofits,Office Manager,No context needed,47500,0.0,USD,NaN,No context needed,United States,Not provided,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
11,2021-04-27 11:03:07,35-44,Education (Higher Education),Deputy Title IX Coordinator/ Assistant Directo...,No context needed,62000,0.0,USD,NaN,No context needed,United States,Pennsylvania,Scranton,11 - 20 years,5-7 years,PhD,Woman,"Hispanic, Latino, or Spanish origin, White"
12,2021-04-27 11:03:09,35-44,"Accounting, Banking & Finance",Manager of Information Services,No context needed,100000,0.0,USD,NaN,No context needed,United States,Michigan,Detroit,11 - 20 years,11 - 20 years,College degree,Man,"Asian or Asian American, White"
13,2021-04-27 11:03:10,25-34,Law,Legal Aid Staff Attorney,non-profit law firm,52000,0.0,USD,NaN,No context needed,United States,Minnesota,Saint Paul,2 - 4 years,2 - 4 years,NaN,Woman,White
14,2021-04-27 11:03:11,18-24,Health care,Patient care coordinator,No context needed,32000,0.0,CAD,NaN,No context needed,Canada,Not provided,Remote,1 year or less,1 year or less,College degree,Woman,White
15,2021-04-27 11:03:11,35-44,Utilities & Telecommunications,Quality And Compliance Specialist,No context needed,24000,500.0,GBP,NaN,No context needed,United Kingdom,Not provided,Lincoln,11 - 20 years,5-7 years,College degree,Man,White
16,2021-04-27 11:03:13,35-44,Business or Consulting,Executive Assistant,No context needed,85000,5000.0,USD,NaN,No context needed,United States,Illinois,Chicago,8 - 10 years,8 - 10 years,Some college,Woman,White
17,2021-04-27 11:03:19,45-54,Art & Design,graphic designer,No context needed,59000,0.0,USD,NaN,No context needed,United States,California,Pomona,21 - 30 years,21 - 30 years,College degree,Woman,White
18,2021-04-27 11:03:21,35-44,Business or Consulting,Senior Manager,No context needed,98000,1000.0,USD,NaN,No context needed,United States,Georgia,Atlanta,11 - 20 years,2 - 4 years,Master's degree,Woman,White
19,2021-04-27 11:03:23,35-44,Education (Higher Education),Assistant Director of Academic Advising,No context needed,54000,0.0,USD,NaN,No context needed,United States,Florida,Boca Raton,11 - 20 years,11 - 20 years,Master's degree,Woman,White
20,2021-04-27 11:03:24,25-34,Health care,Data Programmer Analyst,No context needed,74000,0.0,USD,NaN,No context needed,United States,Pennsylvania,Philadelphia,5-7 years,5-7 years,Master's degree,Woman,White
21,2021-04-27 11:03:24,35-44,Nonprofits,Program Coordinator & Assistant Editor,No context needed,50000,0.0,USD,NaN,No context needed,United States,Not provided,Atlanta,5-7 years,2 - 4 years,PhD,Woman,White
22,2021-04-27 11:03:27,35-44,Nonprofits,Event Planner,No context needed,63000,0.0,CAD,NaN,No context needed,Canada,Not provided,Toronto,11 - 20 years,8 - 10 years,Master's degree,Woman,White
23,2021-04-27 11:03:29,35-44,Government and Public Administration,Researcher,No context needed,96000,1000.0,USD,NaN,No context needed,United States,Ohio,Dayton,8 - 10 years,2 - 4 years,PhD,Woman,Asian or Asian American
24,2021-04-27 11:03:31,25-34,Public Library,Teen Librarian,No context needed,44500,0.0,USD,NaN,No context needed,United States,Florida,Bradenton,5-7 years,2 - 4 years,NaN,Woman,White
25,2021-04-27 11:03:34,35-44,Education (Higher Education),Communications Specialist,No context needed,60000,0.0,USD,NaN,No context needed,United States,Michigan,Ann Arbor,11 - 20 years,1 year or less,Master's degree,Woman,White
26,2021-04-27 11:03:38,25-34,Nonprofits,Program Director,I manage staff members who each manage 8-15 ot...,62000,0.0,USD,NaN,No context needed,United States,District of Columbia,Washington DC,5-7 years,2 - 4 years,College degree,Man,White
27,2021-04-27 11:03:40,35-44,Law,Bookkeeper/Billing Manager,No context needed,48000,4000.0,USD,NaN,No context needed,United States,Maryland,Silver Spring,11 - 20 years,2 - 4 years,College degree,Woman,Another option not listed here or prefer not t...
28,2021-04-27 11:03:41,35-44,Government and Public Administration,Economist,No context needed,140000,0.0,USD,NaN,No context needed,United States,District of Columbia,Washington,11 - 20 years,11 - 20 years,Master's degree,Woman,White
29,2021-04-27 11:03:43,25-34,Engineering or Manufacturing,Research Engineer,No context needed,80000,0.0,USD,NaN,No context needed,United States,Texas,San Antonio,5-7 years,5-7 years,College degree,Woman,White
30,2021-04-27 11:03:44,25-34,Nonprofits,Volunteer and Giving Coordinator,No context needed,39000,0.0,USD,NaN,No context needed,United States,Minnesota,Minneapolis,2 - 4 years,2 - 4 years,College degree,Woman,White
31,2021-04-27 11:03:44,35-44,Media & Digital,Editor,No context needed,125000,0.0,USD,NaN,No context needed,United States,District of Columbia,"Washington, DC",11 - 20 years,8 - 10 years,Master's degree,Woman,White
32,2021-04-27 11:03:45,25-34,"Accounting, Banking & Finance",Financial Advisor,No context needed,230000,0.0,USD,NaN,Commission based,United States,Missouri,St. Louis,11 - 20 years,11 - 20 years,College degree,Woman,White
33,2021-04-27 11:03:46,35-44,"Accounting, Banking & Finance",Accounting Manager,No context needed,110000,15000.0,USD,NaN,No context needed,United States,Virginia,Richmond,21 - 30 years,11 - 20 years,College degree,Woman,White
34,2021-04-27 11:03:54,25-34,Nonprofits,Administrative and HR Manager,No context needed,50000,0.0,USD,NaN,No context needed,United States,District of Columbia,Washington,5-7 years,2 - 4 years,College degree,Woman,White
35,2021-04-27 11:03:55,35-44,Education (Higher Education),Senior IRB Analyst,"State university, higher ed research adminstra...",68000,0.0,USD,NaN,No context needed,United States,North Carolina,Research Triangle,5-7 years,2 - 4 years,Master's degree,Woman,White
36,2021-04-27 11:03:56,18-24,Media & Digital,Reporter,No context needed,41000,100.0,USD,NaN,No context needed,United States,Michigan,Kalamazoo,2 - 4 years,2 - 4 years,College degree,Woman,White
37,2021-04-27 11:03:57,25-34,"Accounting, Banking & Finance",Senior Administrator,No context needed,76000,10000.0,USD,NaN,No context needed,United States,New York,Manhattan,5-7 years,2 - 4 years,College degree,Woman,White
38,2021-04-27 11:03:57,35-44,Government and Public Administration,Staff Services Manager II,"Mid-level manager, team of 13",78000,0.0,USD,NaN,No context needed,United States,California,Sacramento,8 - 10 years,5-7 years,Master's degree,Woman,White
39,2021-04-27 11:03:59,25-34,"Accounting, Banking & Finance",Receptionist,No context needed,37000,0.0,USD,NaN,No context needed,United States,Texas,Dallas,2 - 4 years,2 - 4 years,College degree,Woman,White
40,2021-04-27 11:04:01,45-54,Engineering or Manufacturing,Lead Engineer,supervisor level with no direct reports,100000,50000.0,USD,NaN,No context needed,United States,Georgia,waynesboro,21 - 30 years,21 - 30 years,College degree,Woman,White
41,2021-04-27 11:04:01,35-44,"Marketing, Advertising & PR",Senior Copywriter,No context needed,35000,6000.0,GBP,NaN,No context needed,United Kingdom,Not provided,Liverpool,11 - 20 years,11 - 20 years,College degree,Woman,White
42,2021-04-27 11:04:02,25-34,Government and Public Administration,Manager of Data Integrity and Prospect Research,No context needed,65000,0.0,USD,NaN,No context needed,United States,Virginia,Richmond,5-7 years,5-7 years,College degree,Man,White
43,2021-04-27 11:04:04,25-34,Computing or Tech,Principal Software Engineer,No context needed,187500,5000.0,USD,NaN,No context needed,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,2021-04-27 11:04:04,25-34,Computing or Tech,Intelligence Analyst,No context needed,110000,20000.0,USD,NaN,"Around 20,000 a year in stock",United States,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
45,2021-04-27 11:04:04,25-34,Nonprofits,Project Manager,No context needed,66625,1500.0,USD,NaN,No context needed,United States,Massachusetts,Boston,8 - 10 years,8 - 10 years,College degree,Woman,"Hispanic, Latino, or Spanish origin, White"
46,2021-04-27 11:04:07,35-44,Computing or Tech,Mobile developer,No context needed,144600,2500.0,USD,NaN,No context needed,United States,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,2021-04-27 11:04:09,35-44,Computing or Tech,Product Design Director,No context needed,200850,40000.0,USD,NaN,No context needed,United States,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
48,2021-04-27 11:04:10,25-34,Engineering or Manufacturing,Engineering specialist,No context needed,120000,1500.0,CAD,NaN,No context needed,Canada,Not provided,Vancouver,11 - 20 years,8 - 10 years,College degree,Woman,White
49,2021-04-27 11:04:10,25-34,Retail,"Manager, Total Rewards",No context needed,97500,10000.0,CAD,NaN,No context needed,Canada,Not provided,Toronto,8 - 10 years,8 - 10 years,College degree,Woman,White